### ISSUE TITLE
Blocks not rendering underwater

### ISSUE THREAD

**Issue by Wiezerzz** [Lunatrius/Schematica#101]
I don't know if this is on purpose or not but this makes it very difficult to build things underwater. It would help if the blocks would be visible underwater with an opacity of 85%, that would make it a lot easier.

How it is now: http://puu.sh/l2rha/e0d100c21c.jpg

How it should look(but then underwater): http://puu.sh/l2rfk/1a3a6e9cc4.jpg

**Comment by Lunatrius** [comment]
Add `minecraft:air` to the extra air block list in the config.

**Comment by Wiezerzz** [comment]
I already tried that and also tried adding minecraft:flowing_water but it seems to have no effect.

**Comment by Lunatrius** [comment]
What version are you on?

**Comment by Wiezerzz** [comment]
* LunatriusCore-1.8-1.1.2.29-universal
* OptiFine_1.8.0_HD_U_D5
* Schematica-1.8-1.7.7.138-universal

Running Forge 1.8-11.14.3.1505

My configuration: http://pastebin.com/raw.php?i=wV5yvxEE

**Comment by Lunatrius** [comment]
Fixed in b45723dc232f84244ebd13d311a886e3aa343db9. I'm surprised nobody reported this before, it only ever rendered the overlay but not the blocks.

The fix will be released in a day or two, together with the changes/tweaks to the printer.
