### ISSUE TITLE
Printer not working

### ISSUE THREAD

**Issue by winnipeg23** [Lunatrius/Schematica#103]
Hey I'm using my modpack beta version and the printer won't work plz help. i don want to release this version and the mod printer doesn't work

**Comment by polymetric1** [comment]
Is it a modified version (different from the current state of this repo) or is it a clean unmodified fork? I'd recommend providing more information.

**Comment by winnipeg23** [comment]
the version is the one here http://www.9minecraft.net/schematica-mod/ and the printer button says on but it isn't. forge 1.7.10 10.13.4.1541

**Comment by winnipeg23** [comment]
here a list of my mods in the pack (this is the page) http://www.technicpack.net/modpack/razercraft-12.759117

**Comment by Lunatrius** [comment]
Don't download mods from that website. It's known to distribute outdated an not working versions of mods.

The only official websites are [mods.io](https://mods.io/mods/1008), [mc.lunatri.us](http://mc.lunatri.us/Schematica) and [curse.com](http://www.curse.com/mc-mods/minecraft/225603-schematica).

**Comment by winnipeg23** [comment]
I did same thing I don't always use these site

**Comment by winnipeg23** [comment]
ok i redownloaded the mod on cruse still printer doesn't work

**Comment by Lunatrius** [comment]
Are you on a server? Did you try any other schematic files?

**Comment by winnipeg23** [comment]
fixed I didn't know you need to have a block that you place you blocks on.
mod maker put that in the desc

**Comment by Lunatrius** [comment]
If you mean the fact that blocks require other blocks to be adjacent, that can be toggled in the config.

**Comment by winnipeg23** [comment]
yes
