### ISSUE TITLE
Game crashes on startup

### ISSUE THREAD

**Issue by spikespaz** [Lunatrius/Schematica#104]
Usually I can read the logs, but...
So, [this](https://gist.github.com/spikespaz/f52dbbb755dfc44fc94a) is the crash report.
**EDIT:** I still get the same issue when I remove all the other mods, so forge incompatibility?

**Comment by spikespaz** [comment]
**_RESOLVED:_** It is not compatible with the latest version of Forge. Use Forge 11.14.4.15**63**

**Comment by Lunatrius** [comment]
The issue lies in Lunatrius/LunatriusCore#13 and has been [fixed](https://github.com/Lunatrius/LunatriusCore/commit/f3cecbf5dff19e2dab83e245fe203650b2bb2e7e) for 1.8.8. For 1.8 just use the config option suggested in the issue.
