### ISSUE TITLE
Printer Issue

### ISSUE THREAD

**Issue by f1Lthz4** [Lunatrius/Schematica#106]
First time when I joined the creative server and wanted to build schematic on my, plot printer was only placing blocks where is my crosshair..
After changing some settings printer was working good and I built large schematic with just flying around for 15 mins.
Tomorrow I joining this server again and it again placing blocks only on crosshair position..
Or it's just not working on servers?

**Comment by Lunatrius** [comment]
Given that it's a server this might be a plugin trying to block the placement of blocks that aren't close to the crosshair.

It shouldn't otherwise matter if it's a server or not, it's a client side mod. It doesn't really know (for the most part) whether you're in a SP or MP world.

**Comment by f1Lthz4** [comment]
I'm on mp world. I too think it's anticheat stopping the printer but 1 time it worked pretty well

**Comment by Lunatrius** [comment]
What version of the mod are you using? And was it the same server you connected to or is it possible that it was another server?

**Comment by f1Lthz4** [comment]
Last version of mod and it was the same server

**Comment by Lunatrius** [comment]
Latest version being what exactly? Both `1.8.9-1.7.7.142` and `1.7.10-1.7.6.131` are "latest".

**Comment by Lunatrius** [comment]
If you can give me the exact version you're using feel free to re-open.
