### ISSUE TITLE
Problem with printer

### ISSUE THREAD

**Issue by Leftier** [Lunatrius/Schematica#112]
Sometimes let me use it but sometimes didnt, idk why, isnt a crash.
Sry if my explanation isnt good im french.

**Comment by Leftier** [comment]
Btw im using the lastest 1.8.0 version

**Comment by Lunatrius** [comment]
Does that happen on a server? If so, he server owner most likely disabled the feature.

**Comment by Leftier** [comment]
Yes, happens on a server (also in sp), but sometimes let me use it or not.. so i don't think that the owner disabled that feature

**Comment by Lunatrius** [comment]
I'll need the `fml-client-latest.log` file from when the printer is disabled. Also, some of the earlier Schematica builds had some issues that didn't properly block some features due to a 1.7 -> 1.8 quirk.

**Comment by Leftier** [comment]
I solved the problem, just works when you open the schematic for the first time and then u can enable the printer mode but when you open it again you can't use printer mode.
