### ISSUE TITLE
weird crash when trying to build a schematic from minecraft-schematics.com

### ISSUE THREAD

**Issue by Sailren** [Lunatrius/Schematica#113]
this happened during creation of the ultimate trader from this site

http://paste.ubuntu.com/15019127/

**Comment by Lunatrius** [comment]
Duplicate of #111.

> Tried to reproduce it, but was unable to do so. Could you test the following things:
>  * **is it reproducible in a new world (superflat overworld and/or the end)?**
>  * ~~does it work if you remove ForgeEssentials, moreplayermodels and worldedit?~~
>  * ~~can you reproduce it with the 1.8.9 version?~~
> 
> If you'll use your SP world for testing, make sure you have a backup handy if you plan to continue using 1.8 after you'll be done testing.

**Comment by Lunatrius** [comment]
I assume that 1741+ fixes it, feel free to re-open if it doesn't.
