### ISSUE TITLE
Working issue

### ISSUE THREAD

**Issue by musdale** [Lunatrius/Schematica#117]
Mod version : first release for mc 1.9
Forge version : 1.9 verison

Can't find anyway to start the mod hotkeys doesn't show up in the settings section.
is it me or is there a problem with this version ? i've downloaded latest possible version yet till today 31/03/2016

**Comment by Lunatrius** [comment]
First/latest are not version numbers, there is no "1.9" Forge version either. I'll also need the log file, which should have all required versions included.

**Comment by musdale** [comment]
Alright excuse my laziness i thought they might be enough but you are right, i'll send them over when i get back (probably in 2 hours).
So is it ok if i contact you from here or should i had back to your git page ?



1 Nis 2016 tarihinde 17:01 saatinde, Jadran Kotnik <notifications@github.com<mailto:notifications@github.com>> ?unlar? yazd?:


First/latest are not version numbers, there is no "1.9" Forge version either. I'll also need the log file, which should have all required versions included.

-

**Comment by Lunatrius** [comment]
All replies made to the emails you receive are sent directly to the GitHub issue. Do note that attachments don't work so you'll most likely have to use gist or pastebin.

**Comment by musdale** [comment]
welp there goes my privacy :P, ok as it says's it's forge version 12.16.0.1816 (even though i just downloaded .1817 just a moment ago weird..) lunatris core's version is 1.1.2.33........ while i was writing thisi found something.. you know what, i'm sorry man it was my stupidness :D looks like i kind of forgot to put ur mod to the right file... thank's for all this work thogh this mod is great!

**Comment by Lunatrius** [comment]
Does that mean you fixed the issue or?

**Comment by musdale** [comment]
there wasn't anything to be fixed, i just thought there was.. sorry for bothering u :)

**Comment by Lunatrius** [comment]
Alright then. Closing this as a non issue.
