### ISSUE TITLE
Permission denied (publickey)

### ISSUE THREAD

**Issue by DrakeTM** [Lunatrius/Schematica#118]
When trying to download Schematica using Git, I get an error stating that the remote repository could not be read, and that the permission to access it was denied.  What should I do to get around this?
Output of `$ git clone git@github.com:Lunatrius/Schematica.git`
```
Cloning into 'Schematica'...
Warning: Permanently added the RSA host key for IP address '192.30.252.129' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by Lunatrius** [comment]
You most likely forgot to add your public ssh key to GitHub. You can avoid this error by using the `HTTPS` method to clone the repository, but that will require you to type your username and password every session.

**Comment by DrakeTM** [comment]
Okay, I'm fine with using the `HTTPS`. Thank you.
