### ISSUE TITLE
Crash - NoSuchMethodError: FMLControlledNamespacedRegistry.getId

### ISSUE THREAD

**Issue by Cyanodioxine** [Lunatrius/Schematica#121]
Hello, Lunatrius!

I recently updated my tiny cosmetic modpack to 1.9, and amongst the fun is your mod, Schematica. Upon loading a schematic (any schematic), I get the following crash. I've tried on both SMP and SSP, and both produce the same issue.

[Pastebin](http://pastebin.com/heLq3gDr)

I am using Forge 1.9, version 12.16.0.1826

**Comment by Lunatrius** [comment]
#119
