### ISSUE TITLE
It crashes any time i try to save anything... it worked when i was using 1.8.9 but not 1.9

### ISSUE THREAD

**Issue by brendanub** [Lunatrius/Schematica#124]
[crash-2016-04-09_20.30.57-client.txt](https://github.com/Lunatrius/Schematica/files/211559/crash-2016-04-09_20.30.57-client.txt)

Im VERY new to this... i've looked at other reports and have no idea if this is the same thing and also have no idea what you said in response to them means... can you answer in a way a non-programmer would understand?

**Comment by Lunatrius** [comment]
#119 

Long story short: **use Forge 1816 or earlier**. Check the top of the above issue for more details.

**Comment by brendanub** [comment]
thanks
