### ISSUE TITLE
Java.lang.NoMuchMethodError Help, Can't load schematic (1.9)

### ISSUE THREAD

**Issue by PoxReborn** [Lunatrius/Schematica#132]
Trying to load a .schematic file instantly crashed minecraft.
Using Forge.1.9, Lunatrius Core 1.9, Optifine 1.9 HD Ultra B2.

Crash Report:
Pastebin:  http://pastebin.com/N4bjRf3E
Gist:  https://gist.github.com/PoxReborn/b5f093eca420013891bffb4d256c108a

Haven't tried in 1.8.9. Schematic isn't that large of a build in minecraft.
Thanks for any feedback.

**Comment by Lunatrius** [comment]
#119

Update Schematica and Forge. Also, `1.9` is **not** a **valid** version.
