### ISSUE TITLE
Crash on material list or printer in Schematica 1.7.10 life in the woods renaissance pack

### ISSUE THREAD

**Issue by NickSProud** [Lunatrius/Schematica#134]
https://gist.github.com/NickSProud/60c046916632266c187cf60217b382d3

The client crashed as soon as I tried to look at the materials list, the client also crashes when I attempt to print.
This is on the 1.7.10 version on the Life in the Woods Renaissance pack.

**Comment by Lunatrius** [comment]
Outdated Forge version?

**Comment by NickSProud** [comment]
Yep that was it, Thanks ^_^
