### ISSUE TITLE
[1.9] Crash loading .schematic "net.minecraft.client.renderer.chunk.ChunkRenderDispatcher"

### ISSUE THREAD

**Issue by WiBla** [Lunatrius/Schematica#135]
Hello, I'm getting this error everytime I try to load a .schematic :
`java.lang.NoSuchMethodError: net.minecraft.client.renderer.chunk.ChunkRenderDispatcher`

Using MC 1.9, Forge 1887 (also tried with 1816: missing dependencies), OptiFine 1.9 HD U B2 and Schematica 1.7.7.146

Full minecraft report file here :
http://pastebin.com/az9PHmtn
fml-client-latest.log :
https://gist.github.com/WiBla/899c9825f45bf6b1debf8270bc9ad670

I hate to create new issues but I tried my best to resolve it myself unsuccessfully..
Thanks in advance for your help.

**Comment by Lunatrius** [comment]
Have you tried to remove Optifine? It might be invalidating a Forge patch.

**Comment by WiBla** [comment]
Works like a charm ! Thanks.
