### ISSUE TITLE
cant use mod

### ISSUE THREAD

**Issue by trickey445** [Lunatrius/Schematica#138]
who do I load and make? schematcs?

**Comment by trickey445** [comment]
how*

**Comment by Lunatrius** [comment]
This is not a bug/issue/crash and belongs to the forum thread.

Installing the mod is as simple as dragging the file into the mods folder with Forge installed - the mod will show up on the in-game mod list if done properly.

As for the mod usage, there's a [wiki](https://github.com/Lunatrius/Schematica/wiki) to get you started (topics on the right).
