### ISSUE TITLE
Minecraft crashes when I load a schematic

### ISSUE THREAD

**Issue by DrunkGamer** [Lunatrius/Schematica#145]
**Mod version:** 1.9
**Forge Version:** 1.9-forge1.9-12.16.1.1887
**Operating System:** Windows
**Mod List:**
- LunatriusCore-1.9-1.1.2.33-universal
- Schematica-1.9-1.7.7.144-universal
- OptiFine_1.9.0_HD_U_B3
- The 5zig Mod v3.5.12 for Minecraft 1.9

Crash : http://pastebin.com/vzNy5Hac

**Comment by RedNesto** [comment]
Try without Optifine, Schematica is incompatible with Optifine.

**Comment by DrunkGamer** [comment]
nope, still doesn't work...

**Comment by RedNesto** [comment]
Your Schematica is outdated, try with the latest version: https://mods.io/mods/1008/versions/1170/download

Same for LunatriusCore: https://mods.io/mods/1025/versions/1156/download

**Comment by DrunkGamer** [comment]
OMG thx!!!!! You are awsome!!!

**Comment by RedNesto** [comment]
<3
