### ISSUE TITLE
Crashes when trying to save a schematic

### ISSUE THREAD

**Issue by aksu560** [Lunatrius/Schematica#148]
[crash-2016-05-30_21.34.52-client.txt](https://github.com/Lunatrius/Schematica/files/289974/crash-2016-05-30_21.34.52-client.txt)

Cant save schematics, as it crashes immediately.

**Comment by Lunatrius** [comment]
#119, update Schematica

**Comment by aksu560** [comment]
Ah, Sorry for the wasted time. Thank you.
