### ISSUE TITLE
Schematica Crash When Loading Schematic

### ISSUE THREAD

**Issue by HxCamni10** [Lunatrius/Schematica#150]
Hey y'all
So I have scoured all over here and tried the different fix's that you have told other people but I am getting no luck :/
My GPU drivers are up to date, and I have the most recent version of LunatrisCore and Schematica

I put my crash txt file here, I hope y'all can help!

[crash-2016-06-03_18.22.57-client.txt](https://github.com/Lunatrius/Schematica/files/298592/crash-2016-06-03_18.22.57-client.txt)

**Comment by RedNesto** [comment]
Duplicate of #137 .

Schematica is incompatible with Optifine, remove it and Schematica should work.

**Comment by Lunatrius** [comment]
As @RedNesto said, it's incompatible with the currently released version of Optifine (HD U B1 in your case).
