### ISSUE TITLE
Blocks not showing?

### ISSUE THREAD

**Issue by MERCHIE** [Lunatrius/Schematica#152]
When I load a schematic it only shows the outline.
http://imgur.com/2EkNtBL

**Comment by RedNesto** [comment]
Have you tried without ressource pack ?

**Comment by MERCHIE** [comment]
Yes and it stills happens

**Comment by RedNesto** [comment]
Which version of  Minecraft / Schematica / LunatriusCore  are you using ?

**Comment by MERCHIE** [comment]
Both are 1.9.4 and so is optifine and forge

**Comment by RedNesto** [comment]
What blocks are on the schematic ?

**Comment by MERCHIE** [comment]
stairs, snow, clay, stuff like that

**Comment by RedNesto** [comment]
I've edited the message -> refresh this page. ;)

**Comment by MERCHIE** [comment]
how do i change that? sorry im not great with this stuff lol

**Comment by RedNesto** [comment]
If you don't like make changes directly in the file:

1. go on _Mod Options_ or _Mods_ menu
2. select _Schematica_ then click _Config_ wich is below
3. open the _Rendering_ tab
4. set _Alpha Enabled_ to _false_

**Comment by MERCHIE** [comment]
hmm it already is

**Comment by RedNesto** [comment]
Is the _Reset to Default_ button clickable on the config panel ?

**Comment by MERCHIE** [comment]
no

**Comment by RedNesto** [comment]
Have you reload your world between manipulations ?

**Comment by MERCHIE** [comment]
just tried and nothings changed

**Comment by RedNesto** [comment]
Have you click _Done_ after changes to config ?

**Comment by MERCHIE** [comment]
yeah

**Comment by RedNesto** [comment]
And that doesn't work ?

**Comment by MERCHIE** [comment]
no, maybe ill download them again and try that

**Comment by Lunatrius** [comment]
Closing this - if you're still having the issue, feel free to re-open this ticket.

**Comment by TryHardHusky** [comment]
Came across this issue, Turns out it was the shader I was using. Turn that off and the blocks will show.

**Comment by 341025245** [comment]
I have the exact same issue. 
I re-downloaded schematica and this issue still persists. 
I even tried with an alternate older version of schematica, and it still only shows the outline. 
I'm using the 1.8.9 versions.

**Comment by Lunatrius** [comment]
I no longer support old Minecraft versions, sorry.

**Comment by Flavius2705** [comment]
I have the same problem in 1.12.2 tried everything from above , even reinstaling minecraft , still doesent work ... help ?

**Comment by Lunatrius** [comment]
Have you tried any of the suggested fixes? Shaders, Optifine etc.

**Comment by Flavius2705** [comment]
Yes

**Comment by Flavius2705** [comment]
I am using SK launcher , maybe the launcher its the cause ?

**Comment by Lunatrius** [comment]
It worth trying it with another launcher. Also try to install just LunatriusCore and Schematica.

**Comment by EGURT1** [comment]
@MERCHIE What version of Optifine are you using ?

**Comment by EGURT1** [comment]
@MERCHIE try using this version of optifne 1.12.2 [HD U C9](https://optifine.net/adloadx?f=OptiFine_1.12.2_HD_U_C9.jar)

**Comment by iammeat** [comment]
I'm encountering the exact same issue.  Minecraft 1.12.2 and only Core and Schematica installed.  It is only loading a little over a quarter of my schematic.

Here's a link to the schematic: [IslandBase](https://filebin.net/2ptyhmramvlc2fx2/IslandBase.schematic?t=2aoz4chp)

When I load this [vertical cactus farm](https://filebin.net/2ptyhmramvlc2fx2/CactusFarm.schematic?t=2aoz4chp), it loads without issue, however.

**Comment by Icebluewolf** [comment]
Make sure you are within a 3 block radius of the blocks. So if it is tall you will have to build/fly up to the top. Your fist also might start randomly punching but that is ok.

**Comment by iammeat** [comment]
@Icebluewolf I've tried to print even though the blocks aren't showing, but it won't build any of the invisible blocks.  Any other things I should try?  Did you take a look at the two schematics I attached?

**Comment by Icebluewolf** [comment]
No I can look at it later
But i am new to this mod too so if it just builds a portion of the build I
think what I said erlyer was the issue.

**Comment by Xelbayria** [comment]
Hello, 

I've set the alpha to "False" and set Alpha to "0" as well. nothing works. 
I also have Optifine and Schematica and the core mod. 

here's a picture: 
https://imgur.com/DL4ibSL

do anyone know what's causing it.

**Comment by Aquellare** [comment]
I finally find where the problem is, its in optifine. The mod was working without any problems but when i started to configurate the optifine graphics settings suddenly the blocks stoped showing i dont know exactly what graphic configuration is making the blocks dont show but when i find it i will edit this comment (srry my english sucks) **_SOLUTION: The problem is in Graphics, Performance, Render Regions, Change Render Regions to OFF_**

**Comment by PainXDYT** [comment]
@Aquellare  I turned it off but it still isnt fixed, im on optifine too but it doesnt show any blocks, do you have any other solutions you havent shown, im a bit 2 years late for this but anything new?????? if not, i think i wasted morethan 3 years of building smth for schematica

**Comment by dko1905** [comment]
I recently experienced the same issue on Enigmatica 2: Expert with Optifine.
**SOLUTION: *Graphics* -> Change *Use VBOs* to *OFF***
It does impact performance though
