### ISSUE TITLE
Forge for 1.10

### ISSUE THREAD

**Issue by iScripters** [Lunatrius/Schematica#154]
Will this also work with the newest Forge, for 1.10?

**Comment by Lunatrius** [comment]
Forge should be stable enough for end users next weekend, so a rough estimate would be around that time (around the 3rd of July).

**Comment by Karanruth** [comment]
I just posted #155 , is it safe to assume with stable forge #155  issue will go away too?

**Comment by Lunatrius** [comment]
Closing for obvious reasons (it's out now).
