### ISSUE TITLE
Crashing If I Load a Schematic On 1.9.4

### ISSUE THREAD

**Issue by ItzRichii** [Lunatrius/Schematica#157]
If I load my schemetic  it is 1 sec frozen and then it crash inmeditly plz can someone help me? I'm in 1.9.4

Thanks

**Comment by RedNesto** [comment]
Could you provide the crash report please

**Comment by ItzRichii** [comment]
[crash-2016-06-28_11.44.42-client.txt](https://github.com/Lunatrius/Schematica/files/336704/crash-2016-06-28_11.44.42-client.txt)

**Comment by RedNesto** [comment]
Have you tried without optifine ?

Seems to be a duplicate of #137

**Comment by ItzRichii** [comment]
I'm going to try it..

**Comment by ItzRichii** [comment]
OMG thank you so much.. It works !!

**Comment by RedNesto** [comment]
Cool, so you can close this issue :)

**Comment by ItzRichii** [comment]
ye I was going to do that ;)
