### ISSUE TITLE
[1.10.2] NPE during startup

### ISSUE THREAD

**Issue by IdleGandalf** [Lunatrius/Schematica#165]
I got this crash trying to start Schematica with 1.10.2 and a bunch of other mods. I think it's caused by your's.

http://pastebin.com/a1x27PGn

**Comment by RedNesto** [comment]
Exactly the same as #162 (but in 1.10.2)

I don't know why Lunatrius hasn't released a new version for the fix he has pushed.
The only thing to do is to wait the next update of Schematica.

**Comment by IdleGandalf** [comment]
Oh yea you're right. I didn't search for closed issues, no wonder I didn't find it. Yea ok then let's hope for a new release soon :palm_tree:

**Comment by RedNesto** [comment]
I hope not to get hit by @Lunatrius if I give an (unofficial) patched version.
https://mega.nz/#!rgMyFRrL!KnASaq-epLxCpPVLz-a0psXb9MFSuVJQho6iDMfTBtw

**Comment by Lunatrius** [comment]
It's not the same issue, this happens in `CommonProxy`. **Nothing** on that line should be null. It's a static class call and the event shouldn't be null. Try the new version to check whether it works correctly.

Forgot to start the build on jenkins, it's up now.

**Comment by IdleGandalf** [comment]
I have the version running @RedNesto linked and it's running fine. so I guess it was related to that one in some way.

**Comment by Lunatrius** [comment]
Build 150 has the fix from a0fa6ad8da02ae2c5bee61ccd3b12151920a38ae which should be the proper fix,, by using the proper server instance (it may change in the future).
