### ISSUE TITLE
LunatriusCore, Schematica and ForgeModLoader(FML)

### ISSUE THREAD

**Issue by InfernalBlood** [Lunatrius/Schematica#166]
Hello,
I want to add LunatriusCore and Schematica to ForgeModLoader(FML) since FML is lighter than Forge. Can it be done? If I try to add LunatriusCore and Schematica to mods folder it says "This mod can not be found: Forge: Minimum version required is 11.14.0.1237" even though I put forge 11.14.0.1237 and even higher versions in the mods folder. Can I make Schematica work with Forge FML? Bug Report: http://pastebin.com/Yi2UwDXu

**Comment by RedNesto** [comment]
I think you can't since it's stated in [mods.io](https://mods.io/mods/1008-schematica) that Schematica needs _Minecraft Forge_ to work, not _FML_.

**Comment by Lunatrius** [comment]
FML is no longer developed separately and has been merged directly into Forge. The older versions still require Forge, because FML does not offer the hooks required by Schematica.
