### ISSUE TITLE
Tesselating block crash with some blocks at random

### ISSUE THREAD

**Issue by westlyroots** [Lunatrius/Schematica#171]
**Mod version:** 1.7.8.151
**Forge version:** 1.10.2 2070
**Operating system:** Windows 10
**Mod list:**
  * LunatriusCore-1.10.2-1.1.2.36-universal
  * Schematica-1.10.2-1.7.8.151-universal
  * BetterInventoryMod-1.4.3 v 1.10.2

**Crash report:** http://pastebin.com/TfsW1taw

game logs show tesselating block error, and this happens in realms with flatworlds too at random if someone places a block. even without BetterInventory, it's the same crash and error. from testing it IS schematica as without the mod and just the lunatrius core and nothing else, everything is fine.

**Comment by Lunatrius** [comment]
Does the same thing happen with any schematic? It seems to only affect stairs, I'll have to check out what exactly it going on there and why it's trying to rotate a block/face when rendering.

**Comment by westlyroots** [comment]
it doesnt happen with schematics, I mustve not writed the title correctly at 4 am. XD I meant that some blocks have a chance to tesselate, for example I crash instantly when joining a server because one of the stairs/stone bricks tesselates. soemtimes from someone placing a block tesselates, but personally I never saw it happen from me placing a block nor schematics.

**Comment by Lunatrius** [comment]
Isn't that a Forge bug then? I'm not entirely sure how it's related to Schematica when you don't even load a schematic.

**Comment by westlyroots** [comment]
It works in the newest forge version but is VERY laggy then before.

**Comment by Lunatrius** [comment]
I've went over this and I'm not entirely sure if this is a Schematica issue at all and if it is, how to fix it.

  * Does this happen in single player/other servers?
  * Does this happen without Schematica installed?

**Comment by Lunatrius** [comment]
Closing this due to lack of feedback. From what other modders told me this was indeed a Forge issue and should be fixed in the more recent versions.
