### ISSUE TITLE
 Max Schematic Size?

### ISSUE THREAD

**Issue by 7Arach7** [Lunatrius/Schematica#177]
Sorry if this isn't something that should be under issues, I just didn't know where else to put it. 

I was trying to save a schematic of my base to get a materials count, and schematica kept giving me the error

"There was a problem saving 42 chunks to schematica 16.schematic."

I would use MCEdit but this is on a server (And I have used Schematica boatloads of times before on the server, so I know that schematica works in general).

**Comment by Lunatrius** [comment]
The only limit (besides the *hardcoded* 64k x 64k x 256) are the loaded chunks when connected to a server. There should be more information in the log file `fml-client-latest.log`.

You may also want to try WorldDownloader.

**Comment by Lunatrius** [comment]
Closing this due to lack of feedback. If you still have the crash/error report feel free to post it and re-open the issue.
