### ISSUE TITLE
Undo and Malissis Doors

### ISSUE THREAD

**Issue by MeinKraft** [Lunatrius/Schematica#178]
Forge: 2107
MC: 1.10.2
Schematica: Schematica-1.10.2-1.7.8.152-universal

Tried to undo a paste operation and game crashed with this error report

Not sure if its Malissis Doors causing probs or Schematica, Just thought I'd let you know

http://pastebin.com/znq005j5

**Comment by Lunatrius** [comment]
What exactly did you try to undo? Schematica doesn't appear anywhere in the stack trace, but might be still indirectly causing the issue. Need more details on what you were doing at the time.

**Comment by MeinKraft** [comment]
guy on my server said he was using schematica - he wasnt it was worldedit - sorry.
