### ISSUE TITLE
Can't Download using Git

### ISSUE THREAD

**Issue by TheWoolRedstone** [Lunatrius/Schematica#185]
So when i execute git clone git@github.com:Lunatrius/Schematica.git it brings up this:

> Cloning into 'Schematica'...
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

**Comment by Lunatrius** [comment]
Did you add your public key to your Github account? If not use the `https` url instead of the `git` url.
