### ISSUE TITLE
Can't use printer on multiplayer server

### ISSUE THREAD

**Issue by UDPSendToFailed** [Lunatrius/Schematica#187]
Hi!

I have a bit problem, the printer option simply doesn't work on multiplayer servers, tried to change settings, no success. :( It tries to make blocks, but simply nothing happens, sometimes 1-2 blocks are placed, just flash for a half second, and then disappears... It works well in singleplayer worlds. Placed some blocks manually, won't helped.

Forge 1.11-13.19.0.2180
LunatriusCore-1.11-1.1.2.39-universal
Schematica-1.11-1.7.8.155-universal

Here is a video of the issue:

https://www.youtube.com/watch?v=-UD2uBRTUiY

Forge log:

https://gist.github.com/UDPSendToFailed/a59dd24904339e21f9f3ddef3389b5b3

**Comment by Lunatrius** [comment]
Is there an anti cheat plugin installed on the server? If that's the case the printer will be most likely unusable.

**Comment by UDPSendToFailed** [comment]
Yes, NoCheatPlus. I don't know why and how, but [MCBuild](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-tools/2599886-mcbuild-a-custom-minecraft-client-with-auto-build) works good, but it has much less features than Schematica.

**Comment by Lunatrius** [comment]
Not entirely sure how that client works, but I assume that it moves the mouse around to simulate a normal player.

The problem with the anti cheat plugins is, they check very strictly every block placement. Some of the chests include:
 - is the player looking at the block
 - is the block visible from the player's perspective
 - can the block *really* be placed here (must be placed against a block, etc)

I could add mouse movement to satisfy the first condition, but a lot of blocks would still fail on the second condition. However, adding that would mean that your view point would literally fly all over the place, following the printer, making movement pretty much impossible.

**Comment by UDPSendToFailed** [comment]
Thanks for reply, i build it using preview / ghost mode, that's working nice. :)

**Comment by Lunatrius** [comment]
I mentions camera auto movement, not player auto movement. That has already been put on a possible TODO list in #102, but I don't have enough free time right now to add simple features, let alone something as complex as an AI automated printer.

**Comment by UDPSendToFailed** [comment]
Solved, built it manually, thanks a lot for the mod! :)

**Comment by Lunatrius** [comment]
I'll close this as a duplicate of #102, because the printer feature has been described in that issue.
