### ISSUE TITLE
Blocks not showing correctly in material list

### ISSUE THREAD

**Issue by crobock** [Lunatrius/Schematica#188]
In Schematica on a 1.10.2 server, all blocks in the material list showed correctly.  Using 1.11, the block list shows many of those blocks as "Air".  The blocks in question are, as far as I can tell, mostly flowers and decorative blocks.

**Comment by Lunatrius** [comment]
I looked into this and flowers appear to work just fine. Could you upload the problematic schematic file somewhere?

![2016-12-18_12 59 14](https://cloud.githubusercontent.com/assets/864627/21293349/d10b8150-c521-11e6-9daa-3931f5a393a6.png)

**Comment by Lunatrius** [comment]
This might be related to https://github.com/Lunatrius/Schematica/commit/df7d151f7d7d13d055604c2f104053bd53d356b7 and https://github.com/Lunatrius/Schematica/commit/58310b45c12b6115c11621042af85e366db4d092.

**Comment by Lunatrius** [comment]
Closing as a non-issue. If you can provide the log file feel free to reopen the issue.
