### ISSUE TITLE
Printer not working

### ISSUE THREAD

**Issue by NatalyaAlison** [Lunatrius/Schematica#191]
I'm an admin on a server. The staff and I have been using Schematica to get our server ready to open. Today, when going to use the printer, it didn't work. It showed the toggle 'Printer:on' and 'Printer:off', but didn't actually try to print anything. 

I went into a single player and the same schematic worked.
What can I do to fix my problem? Or is there a way to know if someone may have disabled the feature somehow?

**Comment by Lunatrius** [comment]
Did you install any plugins? Did it work before?

[SchematicaPlugin](https://www.spigotmc.org/resources/schematicaplugin.14411/) is opt-in based, you have to give permission to players in order to use it.

**Comment by Lunatrius** [comment]
Closing as a non-issue. If you can provide the log file feel free to reopen the issue.
