### ISSUE TITLE
Error when loading schematic while forestry is present

### ISSUE THREAD

**Issue by 5stang** [Lunatrius/Schematica#195]
Hi,

Schematics fail to load with [this error](http://pastebin.com/GYryebgu) when attempting to load schematics with Forestry present.  They work normally when Forestry is disabled.  No Forestry blocks in the schematics, only vanilla.  The error originally occurred in a large mod pack, but was confirmed to still occur with only Schematica and Forestry present.

osx 10.9.3
mc 1.10.2
forge 2202
LunatriusCore-1.10.2-1.1.2.38-universal.jar
Schematica-1.10.2-1.7.8.153-universal.jar
forestry_1.10.2-5.2.17.349.jar

Let me know if you need more info.

**Comment by Lunatrius** [comment]
I'll check if there is anything I can do to prevent that from happening.

**Comment by Utildayael** [comment]
Confirmed same issue on Windows. It started after we updated our server pack Forestry to the .349 version, same as 5stang. Was just coming to report issue. :)

**Comment by mezz** [comment]
I believe I fixed this in Forestry, just need someone to confirm for themselves to make sure there isn't something else wrong.

**Comment by 5stang** [comment]
Seems to be working as expected with .351, thanks for the quick fix!

**Comment by Lunatrius** [comment]
Thanks for the swift fix.

Still have to revisit this part of the code at a later time... but closing this issue for now.
