### ISSUE TITLE
Schematic too big

### ISSUE THREAD

**Issue by GovernorCockburnWanker** [Lunatrius/Schematica#196]
I made a schematic which was extremely large but when I tried to open use it, only a small portion of the schematic was intact, the rest of the scheamtic was blank space. I'm not sure how big the intact area but it seemed to be an certain ammount of chunks in it as it appeared to be square. I don't know if has to do with the max size of a scheamtic. All help is apreciated.

-Governor Cockburn-Wanker

**Comment by Lunatrius** [comment]
The client only has information on a small area (whatever is loaded). You should use WorldDownloader if you want to save larger areas of a map.

**Comment by GovernorCockburnWanker** [comment]
alright thanks

**Comment by Lunatrius** [comment]
Going to close this then
