### ISSUE TITLE
Directory for schematics changed to C:\ProgramFiles(86)\Minecraft\games\schematics

### ISSUE THREAD

**Issue by ProNoob135** [Lunatrius/Schematica#197]
This first happened to me in 1.10.2, and is now affecting 1.11.2. Changing the directory though mod options or directly editing the config does not work, they will be reset to this directory. When the game is restarted, it erases all saved schematics in this directory.

**Comment by Lunatrius** [comment]
Fixed in 7120d65887e834e36f205085311242ca273c5487 a while back, have to push out the build for it. In the meanwhile just set the folder to a location on your desktop or some other folder.
