### ISSUE TITLE
Suggestion: Ability to replace a specified material with another material

### ISSUE THREAD

**Issue by pkill-nine** [Lunatrius/Schematica#198]

**Comment by Lunatrius** [comment]
```
/schematicaReplace log[variant=birch] log2[variant=acacia]
```

**Comment by pkill-nine** [comment]
aww that's great :) it just needs to be added to the wiki at https://github.com/Lunatrius/Schematica/wiki/Commands

**Comment by Lunatrius** [comment]
[Added](https://github.com/Lunatrius/Schematica/wiki/Commands#client-schematicareplace-pattern-replacement) it to the wiki. Thanks for the reminder.
