### ISSUE TITLE
Schematica is ignoring server permissions after using single player

### ISSUE THREAD

**Issue by Black-Hole** [Lunatrius/Schematica#199]
If a player is using the save feature in a single player world and then join a multi player server, the Schematica mod is ignoring the permissions sent by the server and allows the saving feature.

Also it would be nice if the server could update the permissions any time, so some features could be enabled or disabled for different worlds.

**Comment by Lunatrius** [comment]
Single player doesn't have anything to do with this. It's most likely a race condition between the permission reset and the packet sent from the server.

The client **always** processes all permission related packets and sets the permissions accordingly. That allows for any plugin sending the correct packet to control what the client can and can't use. If the packet it sent to the client on every dimension change, the client will update the permissions accordingly (requires a custom server plugin though).

**Comment by Black-Hole** [comment]
So I wrote a plugin (with debug output) that sends this packet after the player is fully logged in and on world/server change. The client is ignoring the packet.

To reproduce the issue:
- Connect to a server that disables the save feature (save is OFF and disabled in the client at this point)
- Disconnect from the server
- Start a single player world
- Open the save gui and turn save "ON"
- Save your single player world
- Connect to the server again
- The save feature is now enabled and fully functional no matter how many disable packets the server sends
- (If you manually turn save to "OFF" in the gui, you won't be able to turn it on again, unless using single player again.)

**Comment by Lunatrius** [comment]
Thanks for the reproduction steps, made it really easy to pinpoint the issue. The rendering guide wasn't properly -- also added several extra checks to make sure it doesn't go through anymore.

Test the new build once it's up (should be in a few minutes).

**Comment by Black-Hole** [comment]
Yes, the new version works fine. Thank you!
