### ISSUE TITLE
Enderdragon particle crash

### ISSUE THREAD

**Issue by Syl2010** [Lunatrius/Schematica#200]
I have a crash when the enderdragon create its end particle.

log : https://paste.ee/p/vZowg
fml client log : https://paste.ee/p/MX92d

MC 1.11.2
LunatriusCore-1.11-1.1.2.39-universal
Schematica-1.11-1.7.8.157-universal
Windows 10 64 bits
java 8 update 121

**Comment by Lunatrius** [comment]
How is that related to Schematica? Appears to be a vanilla (maybe Forge) bug.

**Comment by Syl2010** [comment]
I have test with other mods, Minecraft crash only with schematica

**Comment by Lunatrius** [comment]
What do you do when the crash happens?

**Comment by Syl2010** [comment]
i travel the portal or connect at the end, And after the dragon fire its first end ball, my game crash looped.

**Comment by Lunatrius** [comment]
Can you try setting *remove erroring entities* in the Forge config file to `true` and post the log after trying to reproduce the crash again?

**Comment by Syl2010** [comment]
no crash, but the particles is invisible. rendering issue ?

log : https://paste.ee/p/CVBVK
fml client log : https://paste.ee/p/M2vEx

**Comment by Lunatrius** [comment]
That's impossible. I was considering a race condition, but if it persists it's something else. Can you remove Schematica only and try again?

**Comment by Syl2010** [comment]
with the 'remove erroring entities' at true ?

**Comment by Lunatrius** [comment]
You can revert it back to false.

**Comment by Syl2010** [comment]
no crash, and the particles are visible.

log : https://paste.ee/p/MVUqx
fml client log : https://paste.ee/p/TcqMQ

**Comment by Lunatrius** [comment]
Could you check if the same thing happens in single player under the same circumstances?

**Comment by Syl2010** [comment]
All log i posted here are single player tests

**Comment by Lunatrius** [comment]
Could you upload the test world somewhere? Looks like you crash on world load, would make debugging a lot easier.

**Comment by Syl2010** [comment]
link: https://www.dropbox.com/s/w00n1f7kkim34vi/schematica_end_particles_crash.zip?dl=1

With mods, config, options.txt and other logs folder.

**Comment by Lunatrius** [comment]
Thanks, I'll test it later today.

**Comment by Lunatrius** [comment]
This... is a weird bug. I can see what goes wrong, but not why. As a temporary work around you'll have to put the particle option in the setting to `All` when you'll want to use Schematica. I'll have to investigate why the world object is null inside of the `calculateParticleLevel` call...

```java
    private int calculateParticleLevel(boolean p_190572_1_)
    {
        int i = this.mc.gameSettings.particleSetting;

        if (p_190572_1_ && i == 2 && this.world.rand.nextInt(10) == 0) // minimal, this.world == null
        {
            i = 1;
        }

        if (i == 1 && this.world.rand.nextInt(3) == 0) // decreased, this.world == null
        {
            i = 2;
        }

        return i; // all
    }
```

**Comment by Lunatrius** [comment]
Found the issue a lot quicker than expected (thanks to IntelliJ's awesome debugger). I missed a particle spawning override, resulting in vanilla code getting executed instead of my NOOP calls.
