### ISSUE TITLE
Printer dont work

### ISSUE THREAD

**Issue by Kentchi** [Lunatrius/Schematica#202]
I just wanna say that my printer dont work iand i need help xD

[c.pdf](https://github.com/Lunatrius/Schematica/files/788154/c.pdf)

**Comment by Lunatrius** [comment]
The log file in incomplete. Also, use https://gist.github.com/ or https://pastebin.com/, don't upload it as a PDF document...

**Comment by Lunatrius** [comment]
Closing as a non-issue. If you can provide the log file feel free to reopen the issue.
