### ISSUE TITLE
Printer just not working

### ISSUE THREAD

**Issue by SchematicBilly** [Lunatrius/Schematica#204]
I have the latest update of schematica and the printer is working 100% fine offline, in a single player world. However why i try to use the printer on a faction server it doesn't give me the option to turn the printer on, and even when i turn it on manually(setting '(' to toggle printer) it doesn't print. 
Help please? thanks!

**Comment by Lunatrius** [comment]
The server most likely disabled the mod. Upload the `fml-client-latest.log` file to gist/pastebin.

**Comment by Lunatrius** [comment]
Closing as a non-issue. If you can provide the log file feel free to reopen the issue.
