### ISSUE TITLE
Printer not placing

### ISSUE THREAD

**Issue by OZKlutz** [Lunatrius/Schematica#207]
Using schematica in a server where schematica is supported. I'm the only one having issues with printing and I tried changing most of the settings: instant place on/off, adjacent only, etc... Whenever I load a schematic and start printing, most of the blocks I place rollback and turn blue again. Is there an easy fix? 
using version 1.8

**Comment by Lunatrius** [comment]
Upload `fml-client-latest.log` to gist or pastebin.

**Comment by OZKlutz** [comment]
mb it was server side :/
