### ISSUE TITLE
Help Needed

### ISSUE THREAD

**Issue by illdemoteu** [Lunatrius/Schematica#208]
im bad at this kind of stuff but when i have no schematics when i load the gui to load up schematics the game works fine and the gui but when i have a schematic thats in the schematic folder the game crashes

**Comment by Lunatrius** [comment]
Upload `fml-client-latest.log` to gist or pastebin and post the link here.

**Comment by Lunatrius** [comment]
Closing as a non-issue. If you can provide the log file feel free to reopen the issue.
