### ISSUE TITLE
[1.7.10] tooltip

### ISSUE THREAD

**Issue by zzyzzyzzx** [Lunatrius/Schematica#210]
Hello,

so i noticed when i updated to a newer version of schematica (running 1.7.6.131-universal) the tooltip went poof, i see the configs for it, i play and mess with the configs, but i do not see the tooltip anywhere, im doing a massive build and they are really really helpful, any advice?

**Comment by Lunatrius** [comment]
That information was moved to the debug overlay (F3) in version **1.7.6.123**.
