### ISSUE TITLE
Ghost Blocks Not displaying texture!

### ISSUE THREAD

**Issue by Human34** [Lunatrius/Schematica#213]
Im using 1.8 Schematica and its never had a issue, until 1 day randomly I try loading up all different schematics and all of them don't display textures on the ghost blocks!

Proof: 
![screen shot 2017-04-21 at 1 30 09 am](https://cloud.githubusercontent.com/assets/27844705/25264042/13bff582-2632-11e7-837f-9ed7183d372b.png)

**Comment by Human34** [comment]
Note It works fine if I don't have Optifine 1.8 on!

**Comment by Lunatrius** [comment]
You can try playing around with some of the graphic related settings (VBOs on/off, maybe render distance).

Side note: Optifine is not officially supported, nor recommended. It causes graphical glitches with a lot of mods. Other than that, 1.8 is not getting any additional updates.
