### ISSUE TITLE
Small conflict with Applied Energistics 2

### ISSUE THREAD

**Issue by Aw3som3Guy** [Lunatrius/Schematica#216]
When I load schematics on a modified version of Crack Pack, random blocks (tile entities I think) are changed, usually with AE2 blocks, although I think one of the blocks were replaced with tnt heads. There aren't any crash reports, because it doesn't crash, it just is more of a minor inconvenience. Running schematica 1.7.10-1.7.6.131 universal.

**Comment by Lunatrius** [comment]
What was the schematic saved with? The block mapping was most likely never added to the schematic if it was saved using some other tool (mcedit, world edit, etc) or it was stripped out after the fact.

**Comment by Aw3som3Guy** [comment]
I downloaded them from Planet Minecraft, but I think they used mcedit. Thanks

**Comment by Lunatrius** [comment]
That's probably it then, the original schematic format doesn't store the mapping, so it swaps around the block IDs.
