### ISSUE TITLE
Printer not working.

### ISSUE THREAD

**Issue by Hawkard** [Lunatrius/Schematica#218]
I tried to build a house using the printer but it's just not working.
I'm on a singleplayer world. Do I need all the blocks to place it automatically? I tried creating my own schematic with a square of dirt and cobblestone, and it worked. But it didn't work for any other schematic.

I'm on creative and it still doesn't work.

**Comment by Lunatrius** [comment]
Where did you get the schematic? Some of the old schematics contain old blocks that are no longer obtainable in the game. You can test this by placing a block manually: the block will be highlighted red.

**Comment by PhoenixCodes** [comment]
A: schematica didn't work on SchematicXYZ. 
B: schematica did work on SchematicABC.
Conclusion: the issue is schematicXYZ, not the mod.
