### ISSUE TITLE
Crash Report w/ Lunatruis Core & Schematica

### ISSUE THREAD

**Issue by Kylebartaous** [Lunatrius/Schematica#219]
**Mod version:** --LunatriusCore-1.11-1.1.2.39-universal-- & ---Schematica-1.11-1.7.8.161-universal ---

**Forge version:** --forge-13.20.0.2296--

**Operating system:** --windows 10--

**Mod list:**

  * ![modlist 1](https://cloud.githubusercontent.com/assets/11208209/26022253/035f0508-3766-11e7-87c8-31330d91dded.PNG)

  * ![modlist 2](https://cloud.githubusercontent.com/assets/11208209/26022255/07b289ae-3766-11e7-9da0-fec3437c8109.PNG)

**Crash report:** --- ---

%1 Then trying to create / launch a single player world: 

*: [crash-2017-05-12_23.05.44-server.txt](https://github.com/Lunatrius/Schematica/files/998334/crash-2017-05-12_23.05.44-server.txt)

The latest logs

*:  [logs zip.zip](https://github.com/Lunatrius/Schematica/files/998336/logs.zip.zip)

%2 loading into a single player world / multi player server, read comments below *

The crash log:

*: [crash-2017-05-12_23.44.03-client.txt](https://github.com/Lunatrius/Schematica/files/998343/crash-2017-05-12_23.44.03-client.txt)

The latest log:

*:  [latest logs.zip](https://github.com/Lunatrius/Schematica/files/998344/latest.logs.zip)

Extra info & things to say

* 
%1 It seems then using this mod set , then i am trying to make / load up a single player world i get stuck on loading world & having to ctrl-alt-del and close the game with task manger.

%2 Then trying to join a server that is vanilla and or bukkit plugin server ( witch does allow this mod to work since iv seen other people use it right ) it seems to let me log in for about 2-4 sec to be able to see chat and where i am standing then crash me back to the launcher.

%3 My thought of mods that could be causing the crash would be waila , inventory tweaks and or opti define since it seems they been having a bit of problems with latest versions.

**Comment by Kylebartaous** [comment]
Update yep optidefine is broken as shit but still may want to look in to this. dam now i need to bug report opidefine great times ...

**Comment by Lunatrius** [comment]
Closing this as a non issue if it's Optifine. If it's not, feel free to re-open the ticket.
