### ISSUE TITLE
Only the state overlay is rendered

### ISSUE THREAD

**Issue by MewBear** [Lunatrius/Schematica#221]
So, when I try loading up a schematic I only see where the blocks are supposed to go, not the blocks that im supposed to place. Please Help

Example: http://imgur.com/Ly4IBgR

**Comment by Lunatrius** [comment]
Could you try loading a smaller schematic? Could you alto test with Forge, LunatriusCore and Schematica only?

**Comment by Lunatrius** [comment]
This is actually a duplicate of #189
