### ISSUE TITLE
Blue Blocks

### ISSUE THREAD

**Issue by PotatoKinGA** [Lunatrius/Schematica#223]
I have Blue blocks instead of ghost blocks

![screen shot 2017-05-26 at 10 43 34 pm](https://cloud.githubusercontent.com/assets/28982057/26495322/8e04e94c-4266-11e7-9f90-504f0047faf9.png)

How do i fix this???

**Comment by Kylebartaous** [comment]
This is how the render should be showing up, as a blue tint of ghost block so then you toggle printer it knows to go there and place the blocks in that order and spot, if you saying that you having the render stuck on check your settings. also if you not understanding why it a blue tint color so you be able to see it , tho i am not sure if you can change the color for it , my best bet would to do some more research into it with you tube and learn all the bits of the mod. http://prntscr.com/fch182

**Comment by PotatoKinGA** [comment]
But why is it not showing ghost blocks?

I have no idea what block to place without printer

Please HElp!! i need the cannon for a raid in factions

**Comment by Kylebartaous** [comment]
Like i have said you tube how to use the mod watch a couple vids you understand it , and for designs idk look up designs google is right in front you lol

**Comment by PotatoKinGA** [comment]
Do you have an answer to this tho?

**Comment by PotatoKinGA** [comment]
I swear i am so unlucky

**Comment by Lunatrius** [comment]
Try toggling the VBO setting in the options on/off.

**Comment by PotatoKinGA** [comment]
guys i have figured it out. It has to do with other mods you have. For instance i had a bad version of optifine. I got rid of it and it was fine so you have to play around a bit
