### ISSUE TITLE
Schem is not out for 1.12 

### ISSUE THREAD

**Issue by Elias040319** [Lunatrius/Schematica#225]
I know this is not a bug or anything but this is an issue for my faction cause our server is resetting soon and we really need schem for 1.12 cause all our ship ideas is on schem

**Comment by Lunatrius** [comment]
This does not belong on a bug tracker. It will be released when it's done.

**Comment by MrDrummer** [comment]
World edit is functional with 1.12. You can save/paste schematics with world edit, if that's the functionality that you require.

**Comment by PhoenixCodes** [comment]
It's not, schematica does not use or require WorldEdit. That being said,
asking if that's the required functionality implies that Lunatrius would
copy someone else's code. Just, no. Also, poor taste to tell the Dev that
their mod should work because this other one does, without understanding
the first thing about the program. Further bad taste to do so in a closed
bug's comment section.

**Comment by PhoenixCodes** [comment]
I doubt the OPs server is going to allow that, to be honest. I can suggest downloading your portion of the world with a tool that saves chunks from a server as an offline world, so that you can later use schematica on them for rebuilding though?

**Comment by Elias040319** [comment]
We have used schematics with worldedit our own creative server but we are gonna need it for survival


Skickat från min Samsung Galaxy-smartphone.
-------- Originalmeddelande --------Från: MrDrummer <notifications@github.com> Datum: 2017-06-27  12:53  (GMT+01:00) Till: Lunatrius/Schematica <Schematica@noreply.github.com> Kopia: Elias040319 <eliazzm2@gmail.com>, Author <author@noreply.github.com> Rubrik: Re: [Lunatrius/Schematica] Schem is not out for 1.12 (#225) 
World edit is functional with 1.12. You can save/paste schematics with world edit, if that's the functionality that you require.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Lunatrius/Schematica","title":"Lunatrius/Schematica","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Lunatrius/Schematica"}},"updates":{"snippets":[{"icon":"PERSON","message":"@MrDrummer in #225: World edit is functional with 1.12. You can save/paste schematics with world edit, if that's the functionality that you require."}],"action":{"name":"View Issue","url":"https://github.com/Lunatrius/Schematica/issues/225#issuecomment-311323831"}}}

**Comment by Elias040319** [comment]
Im sorry if i offended you but for the first english isnt my first language so i dont understand english to a 100% and for the second i had never used that website so i didnt really know where to post and for the third i dont know anything about programming or coding


Skickat från min Samsung Galaxy-smartphone.
-------- Originalmeddelande --------Från: PhoenixCodes <notifications@github.com> Datum: 2017-06-27  14:35  (GMT+01:00) Till: Lunatrius/Schematica <Schematica@noreply.github.com> Kopia: Elias040319 <eliazzm2@gmail.com>, Author <author@noreply.github.com> Rubrik: Re: [Lunatrius/Schematica] Schem is not out for 1.12 (#225) 
It's not, schematica does not use or require WorldEdit. That being said,

asking if that's the required functionality implies that Lunatrius would

copy someone else's code. Just, no. Also, poor taste to tell the Dev that

their mod should work because this other one does, without understanding

the first thing about the program. Further bad taste to do so in a closed

bug's comment section.
