### ISSUE TITLE
Schematica Works on all servers but This one?

### ISSUE THREAD

**Issue by XWJ1** [Lunatrius/Schematica#231]
I have this problem where schematica works on every server except  this one. Is this server side or Client Side?

**Comment by PhoenixCodes** [comment]
I believe schematica allows for a server-side version that can be set to allow all, nothing, or just overlay. What server is it?

**Comment by Lunatrius** [comment]
The server most likely disabled the mod. Check the logs, you should see a message that says the following: ```
Server capabilities{printer=false, save=false, load=false}
```
