### ISSUE TITLE
Schematica Printer not working

### ISSUE THREAD

**Issue by DedFusion** [Lunatrius/Schematica#232]
first of all great mod 

the mod works for my friend and I got him to send me his files for the mod but the printer doesn't work for me but does for him any ideas why?

**Comment by Lunatrius** [comment]
Are you using it on the same server? Are you able to turn it on at all?

**Comment by DedFusion** [comment]
yes we are and the mod loads the schematics just won't print them for me

**Comment by Lunatrius** [comment]
Does it not work for both of you? Are you on a server? If you are, could you test it in a SP world?

**Comment by DedFusion** [comment]
it works for 2 of my friends but not me and I have the config set the same as them too.
We are on ftb infinity evolved server where I am head moderator

**Comment by DedFusion** [comment]
Sorted it

**Comment by Lunatrius** [comment]
What was the issue?
