### ISSUE TITLE
Java Mod Please

### ISSUE THREAD

**Issue by zudummfuerrwelt** [Lunatrius/Schematica#233]
Hello, im to bad for the Tutorial!
Please sent me a Java date :(((
I want to play with Schematica mod, bad i cant.

**Comment by PhoenixCodes** [comment]
I'll put it bluntly. Get the bleep off github if you can't even... Communicate? Type? English? I dunno. Your words do not make sense in the ways used. This is not the place for requests anyhow. If you are wanting the mod, it's available many other places, GitHub is for development. If you don't know how to do anything development wise, go get the mod from elsewhere, or wait till is officially available for your version of Minecraft.
