### ISSUE TITLE
Printer Issue when moving in redstone build

### ISSUE THREAD

**Issue by KeeganDeathman** [Lunatrius/Schematica#24]
I wanted to build a elevator n my spawn, but it would be underground mostly, so I decided to build it in a SCP world flatland, export it, and print it on the server. But the pistons are having issues staying off, which should fix itself in good time, but also I keep placing the block currently in hand. Help?

**Comment by Sanduhr32** [comment]
This issue reappeared for me. [video download](https://cdn.discordapp.com/attachments/406877088126205952/427291891231621130/2018-03-25_04-14-02.mp4) Its probably not the same kind but its placing and breaking redstone dust in a loop. Please get Schematica out of this nutshell. <3
Minecraft: 1.12.2
Forge: 14.23.2.2618
Schematica: 1.8.0.168
Server: Yes, Modpack, OP, GM1

**Comment by Lunatrius** [comment]
Just disable automatic block breaking as a temporary solution.

**Comment by Sanduhr32** [comment]
I did i just wanted to inform you that it still appears and that you could add mushroom blocks as air blocks since some trolls use them.

Have a great day, best regards,
Sanduhr32
