### ISSUE TITLE
Printer opening dispensers

### ISSUE THREAD

**Issue by Azety** [Lunatrius/Schematica#241]
When i use the printer for a TNT cannon, i keep opening dispensers when a few get placed. This does not go away and is extremely annoying. The dispenser menu opens up more than 5 times per second. Is there any way to fix this problem?

**Comment by Pokechu22** [comment]
Does it happen if you hold shift?

**Comment by Lunatrius** [comment]
What version of the Schematica and Forge are you using?

**Comment by Azety** [comment]
i use em both for 1,11,2 and yeah, it still happens when i hold shift

**Comment by Lunatrius** [comment]
Does this happen in SP or MP (or both)?

**Comment by Lunatrius** [comment]
I can't reproduce the issue. Do you have any other mods installed? A mod list would be great.

**Comment by Lunatrius** [comment]
Closing due to lack of feedback.

**Comment by Lucklessseal375** [comment]
i am having this same issue but for 1.8.9
