### ISSUE TITLE
1.12 multiplayer craft menu

### ISSUE THREAD

**Issue by mcgodbuilder** [Lunatrius/Schematica#244]
Not sure if this is just me, the server or no one has had this issue before. I'm very happy schematica has updated and i started using it. However i noticed that while having a schematic loaded i can not use the crafting menu that has been added in 1.12. hiding the schematic does not change anything. only unloading the schematic gives me back the options.  My game does not crash or anything. i just cant use the new crafting help menu to for example make a full stack of doors or bricks.

Any idea what this is?

**Comment by Lunatrius** [comment]
Have you tested this in single player by any chance?

**Comment by Lunatrius** [comment]
I have tested this in single player and multi player and I can't reproduce the issue. Do you maybe have other mods installed besides Schematica and LuantriusCore?

**Comment by mcgodbuilder** [comment]
I did not have any other mods installed. However during the time i started using it, there seems to have been a "sneaky" update to spigot to fix a exploid bug. This seems to have altered some things so in the end it appears that it was indeed the server it self even though they kept claiming it was not them. They just did not realise there had been an update that altered permission stuff. It works fine now although i feel that the 1.11 version was a lot more stable and reliable on the printer function. It now produces a lot of ghost placing that when you move away dissappear. However that is something entirely different. Sorry to have wasted a little of your time today. I know you are busy and i do hope you will continue making this awesome mod even better
