### ISSUE TITLE
Can't Open Schematics folder ;-;

### ISSUE THREAD

**Issue by DerpySloth** [Lunatrius/Schematica#245]
hi 
 I have been trying to load the schematics but everytime i press (open schematic folder) it doesn't open the folder and the schematic isn't showing up 
please help :-:

**Comment by Lunatrius** [comment]
What version of the mod and Forge? Attach the forge log as well as it should log why the action failed.

**Comment by Lunatrius** [comment]
Closing due to lack of feedback.
