### ISSUE TITLE
Schematica Loads but...

### ISSUE THREAD

**Issue by Shorra** [Lunatrius/Schematica#246]
The schematic works well however the colours of the block happen to do something really weird 
![2017-08-04_12 54 03](https://user-images.githubusercontent.com/30725055/28967896-4f3f700c-7915-11e7-832e-5f504dbc0044.png)

**Comment by Lunatrius** [comment]
I'll at the very least need the mod version and a list of other mods that you might have installed.

**Comment by Shorra** [comment]
![fcc46c8ddeaf87fef9b565cd55695895](https://user-images.githubusercontent.com/30725055/28993643-7c7148fe-79b3-11e7-88c6-0bcab1883e59.png)
Here you good sir

**Comment by Lunatrius** [comment]
In the game options try turning VBOs on/off depending on your current setting. If it still doesn't work try removing OptiFine.

**Comment by Shorra** [comment]
It was VBO which was turn on , I turned it off and it worked, Thank you very much Lunatrius
