### ISSUE TITLE
Is it possible to flip schematics upside down?

### ISSUE THREAD

**Issue by Ninja77677** [Lunatrius/Schematica#249]
I've tried for like 20 mins and I can't get it to flip upside down. any ideas

**Comment by Pokechu22** [comment]
You should just need to make sure that the text next to "flip" is set to "up", and then click "fip".

**Comment by Ninja77677** [comment]
nope, when I click flip while it's set to "up", nothing happens

**Comment by Lunatrius** [comment]
Does the button become red after you click it? You have to hold shift to force a flip operation, by default it only allows a safe flip operation.
