### ISSUE TITLE
.schemmat not saving properly

### ISSUE THREAD

**Issue by athena9008** [Lunatrius/Schematica#252]
When i try to transfer schematics into the folder to load them, my computer wants to open them in other programs while im in minecraft. this happened when i tried to opened the load design with / it said i didnt have anything in the folder. i opened it is and saw my schematic that i downloaded but it was coming up as a white file picture that said dragonstatue.schemat but none of the tutorials explained what to do after putting schematics into the main folder or if it just auto sets up. so far its just sitting there now because my computer started to register it as a adobe file and now it thinks its a krita file(krita is like a free photo shop kinda thing). even when i tried to make my own schematic just to see what would happen all those files are saving as an adobe file now. is there something im missing? i have both the newest versions of lunatrius core and schematic. is there another program that can fix how my computer sees .schemat files?

**Comment by jspanos71** [comment]
It should be a .schematic file. If you got it through discord know that discord changes the extension to .schemat. Rename it and it should work properly.

**Comment by athena9008** [comment]
![files](https://user-images.githubusercontent.com/30961239/29243885-a6395546-7f67-11e7-96b4-1aaa884752dd.jpg)

the thing is this is whats its doing now. the top file is how my game is saving everythign and the second one is how my computer mesesd it up :/

**Comment by athena9008** [comment]
![example 1](https://user-images.githubusercontent.com/30961239/29243922-a2ecbd50-7f68-11e7-92ff-3b0478f57b48.jpg)
![example 2](https://user-images.githubusercontent.com/30961239/29243923-a973b0ca-7f68-11e7-9b15-b011edef2dae.jpg)
![example 3](https://user-images.githubusercontent.com/30961239/29243934-fff4080a-7f68-11e7-9b53-514a38b445da.jpg)


so this is what i'm working with. every time i keep trying to make a new blueprint it doesnt make multiple it just over rides what i have there.

as for the one thats stating it is a schematic file even after renaming it its still not showing up or wanting to still load as an adobe file.

**Comment by athena9008** [comment]
this is what i'm having a hard time with. none of the tutorials state what you have to do with the file after dragging it into the schem folder. and when you go into the / menu it doesnt auto show my blueprint. so i tried to open the schem folder and double click it that way, me thinking i have to select open it for it to show, but again in picture one this is what it wants to do with it. which is why im having so much trouble and that all the tutorials are assuming that everyone just knows what to do which isnt the case. i have never used forge before and it would be better if the main creator or someone actually made a more informative tutorial to show what to do rather then just say "load it up from here and it will be in the quick menu now" which they mean the one from the third picture.

**Comment by Lunatrius** [comment]
I don't know what exactly the issue was, but both the [loading](https://github.com/Lunatrius/Schematica/wiki/Loading-schematic-files) and [saving](https://github.com/Lunatrius/Schematica/wiki/Saving-schematic-files) wiki pages explain how to use the menus. There is not a lot of elements on the GUI so most of them should be pretty straight forward as to what they actually do.
