### ISSUE TITLE
Can't open schematics

### ISSUE THREAD

**Issue by NoScopeProz** [Lunatrius/Schematica#254]
Hello,

I have loaded in many schematics, and they all show up when opening up the select tab. But whenever I select a schematic and click done nothing happens. When I try to manipulate a schematic everything is blanked out and I can't click anything. I do not have Optifine. A screenshot of my mods folder and the versions I am using are attached. I have tried turning VBOs on and off.
On Schematica config, Alpha is set to 1.0 and Alpha enabled is false.

Thanks!
-NoScopeProz

![screen shot 2017-08-17 at 5 49 44 pm](https://user-images.githubusercontent.com/31095795/29406751-8f90827c-8374-11e7-803a-0abde306427f.png)

**Comment by Lunatrius** [comment]
I'll need the log file.

The schematic might be corrupt or the server disabled certain features of the mod.

**Comment by NoScopeProz** [comment]
This was on Singleplayer, also I've tried multiple schematics from a lot of websites. I think the most recent log is attached. Here is the folder of my schematics

[Log.zip](https://github.com/Lunatrius/Schematica/files/1231723/Log.zip)
[schematics copy.zip](https://github.com/Lunatrius/Schematica/files/1231724/schematics.copy.zip)

Thanks!
-NoScopeProz

**Comment by Lunatrius** [comment]
Those are not valid schematic files, they're just HTML files. Re-download the schematic files.
