### ISSUE TITLE
Blur image 

### ISSUE THREAD

**Issue by CorvoO** [Lunatrius/Schematica#258]
sir is this a bug or anything else ? 
![2017-09-02_15 06 29](https://user-images.githubusercontent.com/31563844/29994583-701496bc-8ff0-11e7-8681-3aaf24062932.png)

**Comment by Lunatrius** [comment]
Try turning VBOs on/off. Try removing Optifine.

**Comment by santa4nt** [comment]
I just experienced the same thing. Issue #261 is dup of this, I suppose.

I turned off VBO and that fixed it! No need to remove Optifine, for me. I wonder why this is, though.

**Comment by Lunatrius** [comment]
That happens because Optifine does bad things.

I didn't look into it and I don't really have time to check what Optifine does to mess up the rendering like that.

**Comment by ThePlasmaRailgun** [comment]
@Lunatrius I've tried turning off VBOs, and that fixes the weird polygon problems, but then I still have problems with turning on transparency. Do you know how I might fix this? Also, what exactly does the Z-offset setting do?

**Comment by Lunatrius** [comment]
Sadly not. Optifine does some weird stuff and the mod being obfuscated does not help in any way.

Z offset is the amount that's added to the overlay bounding box to avoid [z-fighting](https://en.wikipedia.org/wiki/Z-fighting).
