### ISSUE TITLE
Game crash on pressing / in 1.12.1

### ISSUE THREAD

**Issue by TrueAsymmetry** [Lunatrius/Schematica#259]
Schematica has worked fine for me in 1.12, but I updated to 1.12.1 today and the game crashes the moment I press on / to try and load a schematic. The screen just freezes, then the game crashes. 

Everything else seems to work fine. I can save schematics, but obviously it's pretty useless if I can't load them after. 

I have tried just about everything I can think of to get this working. I have removed all other mods, so it's just Lenatrius and Schematica, both nothing works :(

**Comment by Pokechu22** [comment]
Can you please post the crash report?

**Comment by TrueAsymmetry** [comment]
I would... if I knew how to obtain a crash report. 

It just says Java SE Binary is not responding, then when clicking Close Program it goes to the Minecraft launcher saying that there was a game crash and an unexpected error occurred. 

How do I get a full crash report? Thanks :)

**Comment by Pokechu22** [comment]
Oh, one of those crashes - they usually don't generate a crash report, and are harder to diagnose...

**Comment by TrueAsymmetry** [comment]
I have tried everything to try and get it working, even installing slightly older versions of Forge 1.12.1, but every time it freezes and crashes when trying to load a schematic. It never even reaches the menu to select a schematic, it just does it the moment I press /. 1.12 worked fine.

**Comment by Lunatrius** [comment]
1.12 and 1.12.1 are almost identical.

Do you have any other mods installed? Did you try to create a new profile?

**Comment by TrueAsymmetry** [comment]
I did have Optifine and World Edit, but I removed those in order to try and get it working. I have created new profiles, updated Java, reinstalled Minecraft, tried older versions of Forge 1.12.1, everything - but nothing seems to work :(

**Comment by TrueAsymmetry** [comment]
Okay, I've managed to get it working. Thank you for your help anyway :D 

I went for a fresh install of Minecraft, deleted everything, all of the folders, settings, even my saves (obviously after backing them up elsewhere), so it was as clean as could be. Now it works :)

**Comment by Lunatrius** [comment]
I wonder if it was a faulty schematic file.Do you still have the schematic files that you had in the folder before you wiped it all?

**Comment by TrueAsymmetry** [comment]
I do have them elsewhere on my computer, yes.

**Comment by Lunatrius** [comment]
Try moving them back into the folder to check if it hangs again.

**Comment by TrueAsymmetry** [comment]
Yup, that did it. I moved them back and it crashed again. I guess it was a bad schematic. TBF, I had 1000s of schematics in that folder. I have been using Schematica for a long time. It's so nice to have it cleaned out.

**Comment by Lunatrius** [comment]
Uhh... the amount of schematics might be the reason why it hangs. I'd suggest sorting them into folders, it should improve loading times. Try splitting them into ~100 per folder and check if it hangs for any of the folders. If it still hangs, trey splitting them up even more.
