### ISSUE TITLE
Add printable liquids

### ISSUE THREAD

**Issue by Regoinss** [Lunatrius/Schematica#260]
Im doing a project and wondering if theres a way where you could print liquids like lava buckets. Maby you could add a setting or if theres another way I would like to know

**Comment by Lunatrius** [comment]
I won't add printable fluids.

The logic required to properly print them is complicated and it can also be heavily abused on multiplayer servers (flooding areas with water/lava).

**Comment by benkillin** [comment]
Would you consider a paid option for this feature?

**Comment by Lunatrius** [comment]
No.

**Comment by benkillin** [comment]
may I then modify your code to do it?

**Comment by ryantheleach** [comment]
Are you asking, do you have that freedom, or if it will be accepted as a PR?

https://github.com/Lunatrius/Schematica/blob/master/LICENSE

**Comment by benkillin** [comment]
considering you selected the MIT license I don't have to ask but I was being courteous

**Comment by adamgerhant** [comment]
@benkillin this is really old but have you made any progress on modifying the code to print liquids? Im currently attempting to do the same

**Comment by benkillin** [comment]
I've made no progress on this sorry - I abandoned my efforts shortly after starting because the reason I wanted it was no longer applicable.
