### ISSUE TITLE
Loading a newly saved schematic shows screwed up blocks

### ISSUE THREAD

**Issue by santa4nt** [Lunatrius/Schematica#261]
Using: Minecraft 1.12.1
MCP 9.41
Forge 14.22.1.2478
Optifine_1.12.1_HD_U_C5

No other mods.

![2017-09-12_13 36 52](https://user-images.githubusercontent.com/152710/30347094-c63d0c82-97bf-11e7-9e22-501057273613.png)

**Comment by Lunatrius** [comment]
#258
