### ISSUE TITLE
Help me please

### ISSUE THREAD

**Issue by GunnerDan** [Lunatrius/Schematica#263]
Every time i try to open my minecraft with schematica it crashes and says im using an unsupported version of the game. what do i do

**Comment by Lunatrius** [comment]
Download the correct version of the mod and/or Minecraft/Forge?

**Comment by GunnerDan** [comment]
i have already done that

**Comment by GunnerDan** [comment]
whenever i load my minecraft the game crashes

**Comment by Lunatrius** [comment]
> crashes and says im using an unsupported version of the game

Upload an image of that error or the crash log itself. You have to download the proper version...

**Comment by Lunatrius** [comment]
Closing due to lack of feedback.
