### ISSUE TITLE
ETA on 1.12.2

### ISSUE THREAD

**Issue by janagyjr** [Lunatrius/Schematica#264]
When will Schematica be available for 1.12.2? A group I'm associated with is working on a new build and we'd love to have use of this awesome mod.

**Comment by Lunatrius** [comment]
This does not belong on the **issue** tracker.

**Comment by janagyjr** [comment]
Well, okay. I get that. Is there somewhere I can ask this and get an answer?

**Comment by Lunatrius** [comment]
The forum thread or twitter.

Just for clarification sake: __1.12__ and __1.12.1__ mods have __no issues__ running on __1.12.2__. It's a bugfix release, nothing changed.

**Comment by janagyjr** [comment]
I didn't know y'all had a forum thread, and I don't know your twitter. Thank you for the information.
