### ISSUE TITLE
Image destorted

### ISSUE THREAD

**Issue by Nytetears** [Lunatrius/Schematica#268]
I am not sure how to explain this but when I try to use Schematica I get a distorted image. It builds find but the image is messed up. see the picture
![distorted image](https://user-images.githubusercontent.com/32307042/30880932-0aecad20-a2d2-11e7-98fa-26939de33060.jpg)

**Comment by Pokechu22** [comment]
Duplicate of #258.

This is caused by optifine, but can usually be fixed by toggling VBOs in video settings.

**Comment by Nytetears** [comment]
Thank you!!!
