### ISSUE TITLE
Making water/lava printable.

### ISSUE THREAD

**Issue by TheKylieBoy** [Lunatrius/Schematica#269]
I know the mod doesn't support this feature, and I know nothing about java, so I was wondering if there would be a way to replace the lava block ID in the mod with something else, like dirt. This way, it would print lava where there is dirt/dirt where there is lava? I'm not sure which way round this would work, and is there an actual reason for lava/water not being printable? 
Even if the solution is temporary, I'd be interested to know. 

Thanks, Kyle

**Comment by Pokechu22** [comment]
The reason why it's unprintable is in #260.

But you can actually swap out blocks already: there's the `/schematicaReplace` command that lets you change one block for another (it doesn't swap them, so directly flipping dirt and lava isn't possible, but you can make all lava dirt while leaving dirt as dirt as well).  Usage is something like `/schematicaReplace minecraft:lava minecraft:dirt`.  It supports block states, so you should also be able to do `/schematicaReplace minecraft:lava minecraft:stained_glass[color=red]`.  It's very important to note that the command name is case-sensitive - `/schematicareplace` will not work.
