### ISSUE TITLE
Suggestion: save chunk you are currently in

### ISSUE THREAD

**Issue by Crucial1** [Lunatrius/Schematica#270]
for those multichunk bases on multiplayer servers which don't load enough chunks to make it a bit faster to save big areas, maybe just a option to quick save with just adding Y co-ordinate

**Comment by Lunatrius** [comment]
What exactly is the end goal of this...?

**Comment by Crucial1** [comment]
To make the saving of large areas a bit easier and faster

**Comment by Lunatrius** [comment]
If you want to save a large area just use WorldDownloader. It's a much better tool for that.

**Comment by Crucial1** [comment]
From what i read it doesn't work on modded server like ftb infinity evolved

**Comment by Pokechu22** [comment]
(I'm the maintainer of world downloader)

Newer versions (4.x series) _should_ support modded servers to some level, in that it attempts to save the block mapping and handle custom dimensions.  However, this isn't heavily tested.  One thing that I can guarantee does **_not_** work is modded containers - the mod doesn't know how to convert the inventory slots into the block entity data.  (But schematica doesn't handle that either if I recall correctly).

**Comment by Crucial1** [comment]
is this for 1.7.10+ versions or 1.10+?

**Comment by Pokechu22** [comment]
The 4.x series only supports 1.10+.  1.7.10 doesn't have any of the compatibility changes - you still _may_ have success with it, but it's luck-based since the block map configuration isn't saved.

**Comment by Lunatrius** [comment]
> One thing that I can guarantee does not work is modded containers - the mod doesn't know how to convert the inventory slots into the block entity data. (But schematica doesn't handle that either if I recall correctly).

Correct. None of the contents are saved at all, unless it's saved in SP or with the command.
