### ISSUE TITLE
1.12.1 concrete (blocks) bug

### ISSUE THREAD

**Issue by Unbr34k4bl3** [Lunatrius/Schematica#272]
Minecraft: 1.12.1
Schematica version: 1.8.0.164
Lunatrius-Core: 1.2.0.41
Worldedit Version: 6.1.8
Forge: 14.22.1.2478
Issue: Concrete blocks don't appear properly within the schematic (see screenshots)
Reproducable steps:

Get afformentioned Mods, make a schematic file with concrete and try using it with schematica.

The game will show different blocks.

Edit: Forgott to mention this is on a SMP server. (Public) but same bug appears in SSP)
2nd edit: I'm not sure if it's an issue with worldedit which makes the schematics or with schematica.
(Sorry if I posted it wrongfully here in advance)
![2017-10-01_22 46 17](https://user-images.githubusercontent.com/29387107/31058838-0d66be1a-a6fb-11e7-8747-27ef199d4ea7.png)
![2017-10-01_22 51 55](https://user-images.githubusercontent.com/29387107/31058847-2583715a-a6fb-11e7-8b40-b4d7321350be.png)

**Comment by Pokechu22** [comment]
Can you attach the affected schematic to this issue?  (You may need to zip it first)

**Comment by Unbr34k4bl3** [comment]
Here ya go.

[floor.zip](https://github.com/Lunatrius/Schematica/files/1348266/floor.zip)

**Comment by Lunatrius** [comment]
The schematic does not contain a block mapping. Currently only Schematica creates schematics that are compatible across different worlds/saves.
