### ISSUE TITLE
Crash when Trying to put a schematic down

### ISSUE THREAD

**Issue by kknightyy** [Lunatrius/Schematica#274]
# What happening is
### So when I double click the schematic I want to put down my mc just crashes 

# So here is what its says

The game crashed whilst updating screen events
The game crashed whilst updating screen events
Error: java.lang.OutOfMemoryError: Updating screen events

# I tried everything even changing the settings

**Comment by Pokechu22** [comment]
> Error: java.lang.OutOfMemoryError

You ran out of memory.  Add more in the launcher, or use a smaller schematic.

**Comment by kknightyy** [comment]
How do I add more memory to Minecraft

**Comment by Lunatrius** [comment]
It depends on the launcher that you are using. A full crash report would be useful to see how much RAM you currently have assigned to Minecraft.

**Comment by Lunatrius** [comment]
Closing due to lack of feedback.
