### ISSUE TITLE
[1.12.2] LAN Player crash using materials button.

### ISSUE THREAD

**Issue by MokahTGS** [Lunatrius/Schematica#284]
MC 1.12.2
Schematica 1.8.0.165
Lunatrius Core 1.2.0.42
Forge 2515

A player in a LAN world is crashing when trying to use the materials button when building schematics.  Press the button and crash.  Report below.  The host machine does not crash.  Just the LAN player.

https://pastebin.com/vFaQpWxT

**Comment by Lunatrius** [comment]
The item stack is null for some item. This is most likely a mod issue. Could try to connecting via LAN by using only Forge, LunatriusCore and Schematica?

https://github.com/Lunatrius/Schematica/blob/b7b078ab12a9daf8e25ad381cbca78dd2b608179/src/main/java/com/github/lunatrius/schematica/client/util/BlockList.java#L56-L78

**Comment by MokahTGS** [comment]
Well we have 200+ mods and this happens on a specific schematic.  It also crashes the host machine if the same schematic is used and the materials button is pressed.  Same crash log.

**Comment by Lunatrius** [comment]
It can be either a normal block (line 59) or a liquid block (line 70). You can just check the `SchematicaMapping` NBT compound of the schematic to get a list of all blocks in the schematic. One of those blocks will be the one causing the crash.
