### ISSUE TITLE
Schematic mod crashing on Mac when I try to save or load Schematics

### ISSUE THREAD

**Issue by Damongirl** [Lunatrius/Schematica#287]
Here are the crash reports.

[crash-2017-11-14_22.32.45-client.txt](https://github.com/Lunatrius/Schematica/files/1473459/crash-2017-11-14_22.32.45-client.txt)
[crash-2017-11-14_22.50.43-client.txt](https://github.com/Lunatrius/Schematica/files/1473460/crash-2017-11-14_22.50.43-client.txt)

If it helps I'm using Magic Launcher to launch mods, but that shouldn't affect it so I have no idea why I can't use it.

**Comment by Pokechu22** [comment]
Appears to be _maybe_ the same issue as #267/#255.  I don't know the details of magic launcher, but it might cause issues with loading mods with access transformers.

**Comment by Damongirl** [comment]
So is there no way to fix it?

**Comment by Pokechu22** [comment]
In both of the other cases, it was caused by the user adding the mod incorrectly in the launcher.  So make sure you've added it correctly, and maybe try a different launcher instead (e.g. multimc).

**Comment by Damongirl** [comment]
I have a pirated account so I don't think Multi MC will work for me.

**Comment by Pokechu22** [comment]
I'm sorry, but we only provide support to users with legitimate copies of the game.

If you wish to purchase the full game, please visit the [Minecraft Store](https://minecraft.net/store).  We will not provide support for pirated versions of the game, these versions are modified and may contain malware.

**Comment by Lunatrius** [comment]
Magic Launcher does not properly load the mods. They may work from inside the `mods` folder, but as Pokechu22 said, no support for illegitimate copies of the game.
