### ISSUE TITLE
Top-Down mode for layer-by-layer - Feature Request

### ISSUE THREAD

**Issue by ThePlasmaRailgun** [Lunatrius/Schematica#288]
I have personally found using schematica in its layer-by layer mode to be one of the greatest tools available to me as a Minecrafter. However, I often misplaced or otherwise mess up when attempting to place a block, and accidentally break something on the layers below me. However, since the layer-by-layer by layer mode only shows a single layer at once, and the all blocks mode shows far too many above the current working layer, I have to individually click through each of the previous layers in order to figure out what I messed up. 

It would extremely useful, not only for this but for other use cases to be able to have a top-down mode for layer-by-layer, where every layer under the current working layer is also displayed, highlighted, and catalogued in the material list. This would ensure that you can check all previously made layers without having to deal with the visual clutter of turning on ALL mode and having tons of unbuilt layers also displayed. 

Anyways, thank you Lunatrius for this amazing mod and all you've done to support it.

**Comment by jspanos71** [comment]
I would love this feature as well! It would make building and checking as you go much easier on complex schematics.

**Comment by Pokechu22** [comment]
That's what it sounds like to me - in addition to `ALL` and `Layers` there'd be a `All below` mode, that works as described.

**Comment by Pokechu22** [comment]
I've submitted a pull request (#289) that adds this.

**Comment by ThePlasmaRailgun** [comment]
@Lunatrius Yeah, I guess you're right. Pokechu's ALL BELOW sounds better.
