### ISSUE TITLE
Saved schematica loads 3/4 of the file

### ISSUE THREAD

**Issue by Chocmonsterjh** [Lunatrius/Schematica#293]
Hi, please fix this issue here is what happened. I saved a schematica on multiplayer (which has worked before) and when I tried to load it the result is 1/4 of the schematica isn't showing. The amount of chunks in the schematica is 21.

Whats happening
![image](https://user-images.githubusercontent.com/34664050/34131347-1927bb12-e4b0-11e7-8b32-a0c0f0c4d2e5.png)

Whats meant to show
![image](https://user-images.githubusercontent.com/34664050/34132063-12daa258-e4b3-11e7-8510-e9d688a4a253.png)

**Comment by Pokechu22** [comment]
Can you attach the schematic here?

**Comment by Lunatrius** [comment]
Also missing at least the version number of the mod and Forge.

**Comment by Chocmonsterjh** [comment]
Version number: 1.12.2 Schematica & Lunatrius 1.12.2 
Forge 1.12.2

**Comment by Lunatrius** [comment]
Sorry for the rather late reply. Where did you stand when you saved the schematic? Was it right next to the area that you've saved or were you far away?

**Comment by Chocmonsterjh** [comment]
I was directly next to the red point

**Comment by Lunatrius** [comment]
Could you try saving the same area again and maybe use a slightly larger area this time? It could have been a one time thing or it's a border case. A screenshot with the coordinates would be great as well.

**Comment by Chocmonsterjh** [comment]
I moved away from the red point and saved the schematic, and it worked! And because you asked Ima add a screenshot with coordinates.
![image](https://user-images.githubusercontent.com/34664050/34843660-f459b034-f773-11e7-9203-7b089b95644e.png)
Thanks for giving me helpful tips to make it work. I will close this issue now.
