### ISSUE TITLE
Issue with the command /schematicaReplace

### ISSUE THREAD

**Issue by Xalopune** [Lunatrius/Schematica#294]
Hello there,

This might be a stupid question but I cannot figure it out. So my problem is that I don't know wich 'code', or better 'id', I have to type in for replacing Quartz Slabs with Stone Slabs. They both have the same id (stone_slab). I've looked online but found nothing. Is this possible, and if so which 'id' should I use?

Sincere,
Xalopune

**Comment by Xalopune** [comment]
Whoops just figured it out :)

I had to use the variant property so it looked like this:
/schematicaReplace stone_slab[variant=quartz] stone_slab[variant=stone]

So this will replace all the Quartz Slabs with Stone Slabs

**Comment by Pokechu22** [comment]
Yep, you use block states for this.

Worth noting that (at least if I recall correctly) doing `stone_slab[variant=quartz]` will target both upper and lower slabs and they should maintain their side after the change.

**Comment by Lunatrius** [comment]
Yes, it does target both and keeps the respective state value (upper/lower).
