### ISSUE TITLE
Alternate key mappings for absent num lock

### ISSUE THREAD

**Issue by landline** [Lunatrius/Schematica#296]
Suggestions for using alternate key-mappings for absent num lock key.  My keyboard does not have the num lock.

**Comment by Pokechu22** [comment]
Schematica doesn't use the numlock key by default (though it does use keys on the number pad).  You can change keybindings in the normal controls screen (I think).  If you're trying to choose keys that aren't on that, consider maybe <kbd>[</kbd> for load, <kbd>]</kbd> for save, and <kbd>\ </kbd> for control (but really, any keybindings will work)

**Comment by Lunatrius** [comment]
I won't be adding an alternate set, because you can change all key binds yourself in the options, under keybindings. You can remap them to whatever you personally like.
