### ISSUE TITLE
Why does my Schematica do this? Ive seen videos where it has actual outline

### ISSUE THREAD

**Issue by Badhangover** [Lunatrius/Schematica#297]
https://gyazo.com/fdf6502c87e4089c1eb11f687168b05c

If you could tell me why that happens that would be great.

**Comment by Pokechu22** [comment]
Most likely an issue with your machine.  If you're using optifine, optifine is known to sometimes cause issues with the mod.

Try toggling VBOs in video settings.

**Comment by Badhangover** [comment]
I took off optifine and it fixed thanks!
