### ISSUE TITLE
Problem block of mods

### ISSUE THREAD

**Issue by okid0kii** [Lunatrius/Schematica#303]
The schematic does not recognize mod's blocks.

Exemple: Sandstone Wall (quark) = Ice (minecraft)

**Comment by Lunatrius** [comment]
What did you use to save the schematic file? Also what Minecraft version?

**Comment by okid0kii** [comment]
Arf i used worldedit. I gonna try to save with schematica tonight and I'll let you know that it works.
Minecraft 1.12.2 2611 forge

**Comment by okid0kii** [comment]
Ok i save with schematica and no problem. Sry for disturbing

**Comment by Lunatrius** [comment]
worldedit does not save the block pallette.
