### ISSUE TITLE
Blocks showing as jagged textures

### ISSUE THREAD

**Issue by ghost** [Lunatrius/Schematica#311]
https://sta.sh/01xgwhbj0mvu
Ive messed with the alpha settings in render as an attempt to fix this and looked around here but didn't find any fixes. Any help appreciated!

**Comment by Pokechu22** [comment]
Looks like a duplicate of #258 -- try toggling VBOs or getting rid of optifine.

**Comment by ghost** [comment]
VBO was the issue! thank you!
