### ISSUE TITLE
Substitution

### ISSUE THREAD

**Issue by peltco** [Lunatrius/Schematica#315]
It would be very nice if i could substitute printing certain materials (like oak wood instead of jungle wood or something like that)

**Comment by Pokechu22** [comment]
This is already a thing; use the `/schematicaReplace` command.  For sub-blocks, you'd use a block state &mdash; `/schematicaReplace planks[variant=jungle] planks[variant=oak]` or such (note that states left unspecified are unchanged, so you should be able to use this on e.g. stairs while preserving orientation).
