### ISSUE TITLE
Schematica MC 1.12.2 not displaying textures properly

### ISSUE THREAD

**Issue by Garyz5** [Lunatrius/Schematica#319]
![image](https://user-images.githubusercontent.com/8870054/37624049-33b7f616-2b9d-11e8-89e1-71f0738151a1.png)

![image](https://user-images.githubusercontent.com/8870054/37623988-f4600c1a-2b9c-11e8-8cf7-22ebd1214f49.png)

Heres a screenshot of the issue. The mini map mod is the only other mod installed and the issue was occuring before it was added. 

Lunatrius/forge/schematica are all up-to-date as of today. 

Please help!

**Comment by Pokechu22** [comment]
Try toggling VBOs in video settings, or removing optifine (if you have it installed).  See #258 (and, apparently, there's also #161)

**Comment by Garyz5** [comment]
Amazing! thanks for the quick reply. turning off VBOs worked instantly.
