### ISSUE TITLE
issue with newest version of optifine and a new setting that was added in that version

### ISSUE THREAD

**Issue by stw222** [Lunatrius/Schematica#321]
Edit by @Lunatrius: you can try to set the VBO option in the settings to OFF or remove Optifine while using Schematica. I am hoping that this will no longer be an issue in 1.13.

---

optifine version (from file name): OptiFine_1.12.2_HD_U_D1
setting that i found to be causing a problem with schematica: "Render Regions" in performance settings

if I set render regions to on, my schematic would only load in partially where it would just show outlines of blocks but not their textures and after a few seconds the game would crash and the launcher would display this error: "java.nio.BufferOverflowException". 
i uninstalled all my mods and narrowed the problem down to a conflict between the newest version of  optifine and schematica.

i was on a server at the time and would join the server (a spigot server with some multi server plugin), load in the schematic i was working on, move it to the correct coordinates and then after 10-20 seconds the game would crash. that schematic was the main part of "the world eater" designed by ilmango

crash report in pastebin: https://pastebin.com/WieGmqrZ

**Comment by Lunatrius** [comment]
I am not willing to add support for Optifine because I do not have the time to reverse engineer the Optifine code to check what is actually going wrong with their "optimizations".

**Comment by shinji257** [comment]
FYI This is bugged over on the Optifine issue tracker right now.

https://github.com/sp614x/optifine/issues/1356
