### ISSUE TITLE
Schematica crashing on opening schematic 

### ISSUE THREAD

**Issue by NutchapolSal** [Lunatrius/Schematica#322]
So I tried to open a schematic on a multiplayer server twice
One time it crashes on opening Manipulate Schematic for the 2nd time and another crashing on schematic load
[crash-2018-03-29_17.22.45-client.txt](https://github.com/Lunatrius/Schematica/files/1859891/crash-2018-03-29_17.22.45-client.txt)
[crash-2018-03-29_17.57.44-client.txt](https://github.com/Lunatrius/Schematica/files/1859893/crash-2018-03-29_17.57.44-client.txt)
(it's something about the renderer)

I opened a schematic before without any problems
Here's the schematic I tried to open (remove .txt)
[ilmango smelter v2.schematic.txt](https://github.com/Lunatrius/Schematica/files/1859905/ilmango.smelter.v2.schematic.txt)

**Comment by Pokechu22** [comment]
Does this issue also happen without optifine?

**Comment by NutchapolSal** [comment]
I tried it without Optifine and it works (same server, around the same location, everything same but w/o Optifine)
Also, I did some testing and:
~~1.Using Optifine makes the texture on the holograms disappear
2.Enabling Fast Render crashes the game~~
3.That is all wrong and the real culprit is Render Regions
If it is enabled then most of the hologram's textures will not show up, only the highlight (chests do show up) and then after a little bit of time it should follow by a crash
4.Happens everywhere, not just multiplayer

**Comment by Lunatrius** [comment]
Yeah, I'm aware of that, but don't have the time to figure out what Optifine is actually doing, as it's closed source. My suggestion for now is to turn that option off while using Schematica or removing the mod altogether.

https://github.com/Lunatrius/Schematica/issues/321#issuecomment-376830977

**Comment by Lovis83854** [comment]
this can be fixed by turning off "use VBOs" in the video settings and will also render the blocks correctly
