### ISSUE TITLE
 I can not print things in the air

### ISSUE THREAD

**Issue by mikkellund** [Lunatrius/Schematica#323]
When I've printed one thing I will put it back somewhere else but the blocks that are just for themselves so without some support from another block they will not be put so I have to make a pole to make it go and put the ..... plz help
![2018-03-30_14 01 31](https://user-images.githubusercontent.com/37930982/38137099-f4cd75a0-3422-11e8-8ac4-8a9eb84c3982.png)

**Comment by Lunatrius** [comment]
This is not a bug. Go into the setting and flip the require adjacent block option. It will no longer require "support blocks" (blocks touching the schematic).
