### ISSUE TITLE
Schematica Crash after load Schematic!

### ISSUE THREAD

**Issue by MrProton657** [Lunatrius/Schematica#326]
Hey there.

Everytime I try to load a schematic, the game crashes. This is the crash report. I'm using the newest version of both forge, lutrinus core thingie and schematica. What's the problem? How could I fix this?
Crash Report: https://pastebin.com/YXZ3jHDr
Pls Help Me! I really like your mod @Lunatrius 

MC version:
1.7.10

Mod Version:
Schematica-1.7.10-1.7.5.120-universal.jar 

LunatriusCore Version: 
LunatriusCore-1.7.10-1.1.2.21-universal.jar

Forge Version:
forge-1.7.10-10.13.4.1614-1.7.10-universal.jar

**Comment by Lunatrius** [comment]
Looks like an incompatibility with shaders. Try turning off shaders and/or removing the shader mod.

**Comment by MrProton657** [comment]
thanks you very much!!! now I can use your mod! (It just work without shadermodcore can you add a shader compatibility)
