### ISSUE TITLE
Loading Schematic not Working on Multiplayer Server

### ISSUE THREAD

**Issue by R0B0H0BO** [Lunatrius/Schematica#328]
I made a part of a castle in singleplayer, then saved it as a schematic and went onto a creative server so i could use WorldEdit. When I tried to print the schematic, it gave me this.
![2018-04-21_18 49 12](https://user-images.githubusercontent.com/38595367/39089438-f8858b8c-4594-11e8-977d-6e186c4ee3c1.png)
This is an image of the original castle.
![2018-04-21_18 49 38](https://user-images.githubusercontent.com/38595367/39089439-f89eae50-4594-11e8-8bee-b2cabc1e7acc.png)
I have never used Schematica before, so it very well might have something to do with the settings. I've seen people use Schematica on this server before, so it's not that.

Edit: I tried deleting and re-downloading Schematica and it gave me the exact same conglomerate of textures.

**Comment by Pokechu22** [comment]
Duplicate of #258; remove optifine or try toggling VBOs.

**Comment by R0B0H0BO** [comment]
Thank you! Turning "Use VBOs" off worked.
