### ISSUE TITLE
Layers arent working

### ISSUE THREAD

**Issue by Schoene619** [Lunatrius/Schematica#330]
I just downloaded this and am new to this mod so I dont think there is an issue with the mod. However, when I load a file onto a world and use the layer function for some reason it wont let me pick a different layer than the 0 layer. Has anyone ran into this issue and know how to fix this?

**Comment by Lunatrius** [comment]
Try binding the keys in the options and use those to see if it works. other than that, using +/- on the UI should work.

**Comment by Lunatrius** [comment]
Closing due to lack of response.

If you're still having the issue, please let me know whether the keybindings work or not. Feels free to re-open the ticket in that case.

**Comment by Schoene619** [comment]
Sorry I forgot to respond. Your suggestion worked perfectly. I think I
figure out why it wasn't working. For some reason my computer sends me
notifications when I'm playing even if I am in full screen mode. So they
are there even though I cant see them. So my computer thinks I am clicking
on that even though clicking on it does nothing.
