### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by RogerPlaysMC** [Lunatrius/Schematica#337]
First off, this is not a bug, but rather a general use/compatibility question. 

I’m starting work on a friend’s Factions server. We want to let players use the printer, but not a certain times (if someone is blowing up their walls we want to disable printer via permissions and worldguard regions). 

Using the SchematicaPlugin you can allow/deny printer via bungee, but afaik Schematica only checks that when the player joins. Before I spend too much time chasing my own tail, is it possible to enable/disable printer on the fly via a Bukkit plugin?  If so, do you have any tips on how to achieve it?

Thanks!

**Comment by Pokechu22** [comment]
As far as I can tell there aren't any restrictions on when you can send [MessageCapabilities](https://github.com/Lunatrius/Schematica/blob/master/src/main/java/com/github/lunatrius/schematica/network/message/MessageCapabilities.java) (the permissions message), so you should be able to send it at any time and change the current permissions (and things will enable/disable as needed).  Here's [how schematicaplugin formats it](https://github.com/Lunatrius/SchematicaPlugin/blob/b799e081af46df7584b5a1b88475f63279567010/src/main/java/com/github/lunatrius/schematica/plugin/SchematicaPlugin.java#L45-L57).

There probably isn't an existing way of doing it, but I think it'd be entirely possible to implement it.

**Comment by Lunatrius** [comment]
I haven't tested it, but the way it's coded right now it should allow you to change it on the fly, assuming that a plugin like that exists. The only thing that might not get instantly disabled in the printer if it's already running.
