### ISSUE TITLE
Blocks don't show up?

### ISSUE THREAD

**Issue by 341025245** [Lunatrius/Schematica#342]
![2018-06-01 1](https://user-images.githubusercontent.com/38593200/40839410-6d41224c-6570-11e8-9faf-616e88bd6417.png)
![2018-06-01](https://user-images.githubusercontent.com/38593200/40839414-723ee388-6570-11e8-95b6-1d3d996403b4.png)
for some reason, the blocks don't show up.
is this a bug?

**Comment by 341025245** [comment]
Also, I've already tried turning off my resource pack. DOESN'T WORK.
also my rendering settings are all on default.

**Comment by 341025245** [comment]
Hello, can any1 help?

**Comment by jspanos71** [comment]
Try turning VBO's off.

**Comment by 341025245** [comment]
What are vbos?

**Comment by jspanos71** [comment]
It is a feature within optifine. Check settings or remove optifine and see if that is the issue.

**Comment by Pokechu22** [comment]
VBOs are actually a vanilla feature, but optifine's implementation causes some issues.

**Comment by 341025245** [comment]
Oh ok, it works now.
Tnx!
