### ISSUE TITLE
Save button is missing

### ISSUE THREAD

**Issue by remclave** [Lunatrius/Schematica#343]
Using the most recent releases of Schematica and LunatriusCore. The save button is missing. I don't have the fml-client-latest.log on my client. No clue why.

![saveschematica image](https://user-images.githubusercontent.com/31051239/40882030-068fe150-669c-11e8-994a-9faeed0652e7.png)

**Comment by Lunatrius** [comment]
Could you try different versions of Forge? I'm not sure why it would not show up properly, unless you downloaded the mod from something else than curse, mods.io or mc.lunatri.us

**Comment by remclave** [comment]
My apologies. I just learned how to navigate my way inside github. I will check.

**Comment by remclave** [comment]
Not sure if it was a Forge issue but it's working again. the save button is back. This issue is now closed. Thank you for your patience.
