### ISSUE TITLE
/schematicaReplace not working (sometimes)

### ISSUE THREAD

**Issue by soepie7** [Lunatrius/Schematica#347]
If one makes a .schematic using Schematica, the schematics can be used with different modpacks (the blocks not in the new pack will become air)

However, when using MCEdit to make a .schematic, all block IDs get randomly changed for new ones, and /schematicaReplace does not work for those blocks, saying it replaced 0 blocks, while I used F3 to get the exact block id it shows me.

As to why I don't use Schematica to get the .schematic: when I did that on a 1.7.10 pack to use the schematic on 1.12, I couldn't rotate the schematic.

EDIT: trying to set the first argument of the command to the block ID it had before it was changed in the .schematic file does not work either.

**Comment by Lunatrius** [comment]
Schematica saves a block to ID mapping into the schematic, to allow the saves to be cross save compatible. Other tools do not read nor write to this property so the blocks usually get jumbled up with random blocks.

**Comment by soepie7** [comment]
I found out 2 more things:
- .schematic files made with Schematica don't jumble up the blocks when used in different modpacks it seems, only when made by MCEdit.
- Placing the block that Schematica asks for, in the case of jumbled-up blocks, still counts as 'wrong' while F3 shows the same block for Schematica and the one placed.

Btw, the issue is not the jumbled-up IDs, but the fact that /schematicaReplace doesn't work on them, making it impossible for me to fix them.

**Comment by soepie7** [comment]
![image](https://user-images.githubusercontent.com/21133200/41375571-c72f700c-6f56-11e8-859c-747edd915bc2.png)

**Comment by Lunatrius** [comment]
What's the exact command that you're using?

**Comment by Lunatrius** [comment]
Closing due to lack of feedback.
