### ISSUE TITLE
Printer Not Working?

### ISSUE THREAD

**Issue by Debilitate** [Lunatrius/Schematica#349]
Hello,

I've recently downloaded schematica today.

While schematica works like a beauty, printer is the opposite.
Printer won't work for 1.7.10.
(What I've downloaded)
LunatriusCore-1.7.10-1.1.2.21-universal
Schematica-1.7.10-1.7.6.131-universal

Although schematica works, there isn't any control options for printer.
![schematica2](https://user-images.githubusercontent.com/40303526/41482867-d38db5c4-70ce-11e8-8de3-b04ca3c9ef36.JPG)

Also, when I try to configure printer it's missing an option too:
![schematica3](https://user-images.githubusercontent.com/40303526/41482920-08a9f83a-70cf-11e8-9350-403823b92031.JPG)

Thank you for your time.
regards,
Debilitate

**Comment by Lunatrius** [comment]
Are you trying to use it on a server? If so, could you test it on SP as well?

**Comment by Lunatrius** [comment]
Closing due to lack of feedback.
