### ISSUE TITLE
How to copy an area (including NBT data) server-side?

### ISSUE THREAD

**Issue by Xaviite** [Lunatrius/Schematica#351]
We have a test server with large regions of command blocks, signs with click events, filled chests etc.

When we put the schematics in through worldedit (//schem load [schematic] -> //paste) it doesn't copy over the commands inside the command blocks. Is there a plugin or server-side mod that can be used to copy over schematics with all NBT data (including commands in command blocks)?

**Comment by Lunatrius** [comment]
How was the schematic itself saved?

**Comment by Xaviite** [comment]
@Lunatrius It was saved using the client-side schematica mod. The schematics were then put into the relevant place of the worldedit plugin to be pasted in.

**Comment by Lunatrius** [comment]
That will not work. The client has no idea about a lot of the NBT data associated with blocks/items. You'll have to use the schematicaSave command or save the schematic using a different tool to preserve the NBT data.

**Comment by Xaviite** [comment]
May I ask what mods can use this command and preserve the NBT data? Is worldedit capable?

**Comment by Pokechu22** [comment]
You can install schematica on the server and use the `/schematicaSave` command.  MCEdit should also save it, and I think worldedit will too.

**Comment by Xaviite** [comment]
Oh you're right! For anyone reading this who uses worldedit with schematica:

//copy
//schem save [name]
//schem load [name]
//schem paste
