### ISSUE TITLE
Printer Not Working

### ISSUE THREAD

**Issue by spaceoio** [Lunatrius/Schematica#354]
Im on my own private server testing out bases for factions the first base worked perfectly fine then when I downloaded another schematic and tried to print it it wouldn't print.

**Comment by Lunatrius** [comment]
What version? Was it the same server? Was it single player?

**Comment by spaceoio** [comment]
It was on my private server on version 1.12.2

**Comment by spaceoio** [comment]
Plugins are:
        WorldEdit and EssentialsX

**Comment by Lunatrius** [comment]
Can you remove all plugins and try again?

**Comment by spaceoio** [comment]
Sure.

**Comment by spaceoio** [comment]
It is still not working.

**Comment by Lunatrius** [comment]
Can you upload the log file of the client to gist/pastebin?

**Comment by spaceoio** [comment]
Sure

**Comment by spaceoio** [comment]
Ya idk how to sorry.

**Comment by spaceoio** [comment]
[latest.log](https://github.com/Lunatrius/Schematica/files/2168851/latest.log)

**Comment by spaceoio** [comment]
FIxed Thanks for helping anyway :)

**Comment by Lunatrius** [comment]
What was the issue?
