### ISSUE TITLE
InGameInfoXML-1.8.9-2.8.1.80-universal error

### ISSUE THREAD

**Issue by Jonzka98** [Lunatrius/Schematica#355]
Whenever I start my minecraft I get this error 
![download](https://user-images.githubusercontent.com/40812036/42251830-496b2728-7f42-11e8-9b26-dc25fcafd4d4.png)

And I have LunatriusCore-1.8.9-1.1.2.32-sources in my mods folder!
I need help :D

**Comment by Pokechu22** [comment]
`LunatriusCore-1.8.9-1.1.2.32-sources.jar` would be the source code for the mod.  You want just `LunatriusCore-1.8.9-1.1.2.32.jar` (also, note that 1.8.9 is rather old)

**Comment by Lunatrius** [comment]
What Pokechu22 said, download the universal file instead.

Also, wrong issue tracker for IGI...
