### ISSUE TITLE
Cannot save

### ISSUE THREAD

**Issue by Galathdra** [Lunatrius/Schematica#360]
So, I created a twitch profile with Inv tweaks and Schematica, right? So I created a ship in creative and want to port it over to my survival. The only problem is, for whatever reason when I hit the off button after pulling up the red/blue point menu, it doesn't change. It just stays there. I've tried restarting the client, but that didn't do anything.

**Comment by Lunatrius** [comment]
Can you take a screenshot of the UI?

**Comment by Galathdra** [comment]
I asked around, and it seems that Schematica didn't work. Sorry for
bothering you :(

**Comment by Lunatrius** [comment]
If it's a server it may have disabled the mod.

**Comment by Lunatrius** [comment]
Closing due to lack of feedback.
