### ISSUE TITLE
Printer button not pressing

### ISSUE THREAD

**Issue by XxTealdragonxX** [Lunatrius/Schematica#362]
When I go to click the Printer button it highlights but when i try to click it nothing happens no sound no nothing.  It just won't turn on!!  Please help!!!

**Comment by XxTealdragonxX** [comment]
I got it to work but now it isnt printing anything.

**Comment by Lunatrius** [comment]
Are you trying to do this on a server?

**Comment by Lunatrius** [comment]
Closing due to lack of feedback.
