### ISSUE TITLE
Schematica not printing for me Both SP and MP 1.8.9

### ISSUE THREAD

**Issue by FacetedAF** [Lunatrius/Schematica#364]
Hey, I kept searching other issues about printer not working but none of them worked for me yet.
I am using Cosmic client 2.0 with schematica. All of schematica works for me besides the printer section. Might it be because of the (modpack) since the server allows printer i have no idea what to do.

**Comment by FacetedAF** [comment]
Okay i got it to work i can now click the print button and it makes movement. Now the only problem is that the blocks aren't placing. I tried all the block placement options but none work

**Comment by Lunatrius** [comment]
Test if it works with only Forge, LunatriusCore and Schematica.

**Comment by Lunatrius** [comment]
Closing due to lack of feedback.
