### ISSUE TITLE
[1.7.10] Schematica Printer Not Working

### ISSUE THREAD

**Issue by ThatsAwesom** [Lunatrius/Schematica#366]
There are no buttons for the printer, which is what I need. I am using Schematica 1.7.6.124 for Minecraft version 1.7.10. Please help me

![image](https://user-images.githubusercontent.com/41645636/43155738-0b7c2e3a-8f2d-11e8-94e3-0d2362640485.png)

**Comment by Lunatrius** [comment]
You turn the printer on in the manipulation GUI.
