### ISSUE TITLE
Printer Not Working! BLOCKS NOT SAVING! PRINTER NOT LOADING! (FIXED!)

### ISSUE THREAD

**Issue by WolvPlayz** [Lunatrius/Schematica#367]
When I use schematica I upload a schematic and press print. It looks like it is placing it but then doesn't place anything. It doesn't crash my Minecraft or anything.

**Comment by WolvPlayz** [comment]
Im in creative on my server as well.

**Comment by WolvPlayz** [comment]
I fixed it BUT it crashes after doing about 10 blocks. It says sending too many packets. How to fix that?

**Comment by WolvPlayz** [comment]
ALL FIXED! It was a viaversion problem! Just turn max-pps and the one below that to -1!

**Comment by WolvPlayz** [comment]
SO ANOTHER PROBLEM! It places the blocks but it doesn't actually place them. BASICALLY, it shows there placed but when i go off and go back on its ALL gone!

**Comment by WolvPlayz** [comment]
FIXED! HAD TO TURN ADJACENT BLOCK TO TRUE AS IM USING 1.8+!

**Comment by WolvPlayz** [comment]
ANOTHER PROBLEM! I built it and then saved the world and went off my server and then I went back on and some blocks (about 200 out of 40,000) were missing so I filled them in and went offline again and I came back and a different approx 200 blocks were missing again! HOW DO I FIX THIS?!

**Comment by WolvPlayz** [comment]
@Lunatrius @ShaRose @Tatara88 @ThranMaru @cltnschlosser

**Comment by Tatara88** [comment]
Why the heck did you tag me?? I don't believe I'm mentioned as staff and I only made a minor pull request over 5 years ago...

**Comment by WolvPlayz** [comment]
@Tatara88 It says ur staff on @

**Comment by Lunatrius** [comment]
That is a desync issue and I'm not sure what could be done to fix that, other that making the printer go slower. That usually prevents it, but not 100% of the time. It seems to be something with the server validating your block placements.

**Comment by WolvPlayz** [comment]
I have slowed the printer down. I will keep this issue updated if it does/doesn't work.

**Comment by WolvPlayz** [comment]
UPDATE: Workes fine now. Thanks
