### ISSUE TITLE
Schematic cuts off part of the schematic, while the box covers the entire schematic

### ISSUE THREAD

**Issue by JPerkinsT19** [Lunatrius/Schematica#371]
I have had no problems with schematica in the past, but when I make the schematic for this structure and attempt to load the schematic, it does not fully load. Here is a screenshot which should be helpful:

![image](https://user-images.githubusercontent.com/42156846/43743420-bd5ddad8-99a3-11e8-8b41-0ab825da32f8.png)

I have tried making a new schematic several times, have tried loading on multiple different worlds, always with the same result. I have toyed with the mod config settings, no luck. Reset to default, still no luck. I have tried everything I can think of to do, but to no avail. How can I fix this?

Thanks!
Jacob

**Comment by Lunatrius** [comment]
Does the same happen if you stand in the middle of the schematic when you create it?

**Comment by JPerkinsT19** [comment]
How do you stand in the middle of the schematic? When I select it from the menu of schematic files, it automatically forms with me standing near the corner.

**Comment by Lunatrius** [comment]
When you're saving it. It seems to be a decently sized schematic, so it might be getting cut off if you stand too far away.

**Comment by JPerkinsT19** [comment]
That fixed it! Thanks!
