### ISSUE TITLE
Crash when loading schematic

### ISSUE THREAD

**Issue by soepie7** [Lunatrius/Schematica#377]
The game seemed to be crashing when the schematic was putting its overlay over a specific block.

The game crashed whilst tesselating block in world
The game crashed whilst tesselating block in world
Error: java.lang.IllegalArgumentException: Cannot set unlisted property net.minecraftforge.common.property.PropertyFloat@375b9a7a to NaN on block extratrees:binnie.wine.carrot, it is not an allowed value

**Comment by Lunatrius** [comment]
That's useless information, I'll need at the very least the console log, preferably the Forge log.

If I had to guess, try removing Optifine or turn off VBOs in the settings.

**Comment by Lunatrius** [comment]
Closing due to lack of feedback.
