### ISSUE TITLE
Not have enough materials.

### ISSUE THREAD

**Issue by rafaelrfreitas** [Lunatrius/Schematica#380]
Hello I just installed schematica, in minecraft 1.8.9, now everything works except printing.
When I check materials it's all 0 even tho i have all I need.

I'm using this forge: 1.8.9-Forge1.8.9-11.15.1.1902
And this schematica: Schematica-1.8.9-1.7.7.142

**Comment by Lunatrius** [comment]
That shows the build progress not materials in your inventory.
