### ISSUE TITLE
Server api documentation

### ISSUE THREAD

**Issue by Photon-GitHub** [Lunatrius/Schematica#381]
It was rather difficult for me to implement the server api (disabling certain features of Schematica) as I couldn't find any proper documentation of all the features the mod provides.
I would appreciate a wiki page which explains the api or a link to a documentation page if it managed to stay hidden from me.

Thanks in advance.

**Comment by Lunatrius** [comment]
https://github.com/Lunatrius/Schematica/wiki/Simple-Block-Codes
https://www.spigotmc.org/resources/schematicaplugin.14411/

**Comment by Photon-GitHub** [comment]
Thank you.
