### ISSUE TITLE
Anyone else having this issue?

### ISSUE THREAD

**Issue by Mystiiera** [Lunatrius/Schematica#383]
Uh, so I'm having a issue with my schematics. The whole thing is very glitched... and I don't know how to fix it. I've tried everything it suggested on the website. But it doesn't work. So if anyone can help me solve this issue..
![2018-09-07_20 30 32](https://user-images.githubusercontent.com/43081932/45248915-e0457e00-b2dc-11e8-9f02-7fc982658c98.png)

**Comment by Pokechu22** [comment]
See #258.  Caused by optifine, but it's sometimes fixed when you toggle VBOs.
