### ISSUE TITLE
My Minecraft crashes after a print

### ISSUE THREAD

**Issue by XiseAbyss** [Lunatrius/Schematica#391]
[crash-2018-10-13_02.06.02-client.txt](https://github.com/Lunatrius/Schematica/files/2475678/crash-2018-10-13_02.06.02-client.txt)
This is my crash log I've gone through it and I have no idea what is causing the crash. Any help would be awesome

**Comment by Pokechu22** [comment]
Duplicate of #321.  This is caused by optifine, and can be solved either by removing optifine or turning off VBOs.  (`at VboRegion.drawArrays(VboRegion.java:297)` is optifine code, though that isn't particularly obvious because for some reason optifine doesn't use a package there)

**Comment by XiseAbyss** [comment]
Oh, thanks I'll try that
