### ISSUE TITLE
Render Issue Crash

### ISSUE THREAD

**Issue by vanjmali** [Lunatrius/Schematica#398]
Every time I load a schematic using schematica it works fine for 10-20 seconds and then crashes  no matter what with error:
[crash-2018-11-03_16.30.47-client.txt](https://github.com/Lunatrius/Schematica/files/2545115/crash-2018-11-03_16.30.47-client.txt)
Is there any idea how could I fix this?

**Comment by Lunatrius** [comment]
Disable VBOs in the settings. It should work fine after. If it still doesn't work, try removing Optifine.

**Comment by vanjmali** [comment]
Works fine after disabling VBOs. Thanks!

Also, it was rendering blocks wrong until I disabled Render Regions in Optifine settings! ^^
