### ISSUE TITLE
Printer not printing at all for me

### ISSUE THREAD

**Issue by LiamTheis** [Lunatrius/Schematica#40]
Hi there! Im having a weird issue with the new 1.7.10 version of Schematica. It seems that when I enable the printing function of the mod, nothing prints. I've tried in SMP and in single player. I've made sure that it was enabled and that I had all the required items in my hotbar.

So Im wondering why this might now be working? Im using 10.13.0.1187 Forge and I've tried the print function in both survival and creative inventories.

Thanks for the help!

**Comment by v3n0m111617** [comment]
i load the shematic then turn printer on but it wont print and says i have no materials but i do have the materials can u help

**Comment by Icebluewolf** [comment]
I Had The Same Problem When I Was Making Something That Floats And I Had To Connect it to the ground with cobblestone than i mined the cobblestone. Hope This Helps

**Comment by LincT** [comment]
I found even better, go to mod configuration, turn "place adjacent only" off
