### ISSUE TITLE
Custom Modpack Crashes

### ISSUE THREAD

**Issue by RYRY001** [Lunatrius/Schematica#403]
I added schematica mod to my small modpack for 1.12.2 and the game crashes whenever I have a schematic open and trying to place blocks. I also just see the outline but nothing else. Here is the crashlog: https://pastebin.com/LmN9h7uG

**Comment by Lunatrius** [comment]
Try disabling VBOs in the settings.

**Comment by RYRY001** [comment]
> Try disabling VBOs in the settings.

Thank you so much, that fixed it.
