### ISSUE TITLE
Server detection

### ISSUE THREAD

**Issue by ShayBox** [Lunatrius/Schematica#434]
Servers are detecting the schematica mod and blocking login entirely, I don't know if this is an intentional packet the mod is sending or not but it should be fixed/removed.

**Comment by DoNotSpamPls** [comment]
As a developer of a plugin that blocks the Schematica mod, I don't think the packet should be removed. However, the mod is listening for special packets sent by the server that can gracefully disable the mod without blocking login entirely. So really, it's not an issue with Schematica, but rather with shoddy code written by some plugin developer(s).

**Comment by ShayBox** [comment]
I'm closing this issue as I don't see this changing and it's been open for over a year, but
The intention is to block logging in if the user has the mod installed, mods that indicate to the server will always have this problem, the solution is to only have server -> client communication to configure the mod, nothing client -> server for servers to misuse, otherwise mods like SchematicaHider will come along to disable the respectful communication entirely.
