### ISSUE TITLE
Game Crashes after a couple 10's of seconds after loading Schematic

### ISSUE THREAD

**Issue by dcm2610** [Lunatrius/Schematica#445]
No matter what size the schematic is, the game would crash leaving me with this error every time.

>  ---- Minecraft Crash Report ----
> 
> WARNING: coremods are present:
> Contact their authors BEFORE contacting forge
> 
> // Daisy, daisy...
> 
> Time: 6/24/19 9:01 PM
> Description: Unexpected error
> 
> java.nio.BufferOverflowException
> 	at java.nio.Buffer.nextPutIndex(Buffer.java:521)
> 	at java.nio.DirectIntBufferU.put(DirectIntBufferU.java:297)
> 	at net.optifine.render.VboRegion.drawArrays(VboRegion.java:299)
> 	at net.minecraft.client.renderer.vertex.VertexBuffer.func_177358_a(VertexBuffer.java:50)
> 	at com.github.lunatrius.schematica.client.renderer.chunk.container.SchematicChunkRenderContainerVbo.func_178001_a(SchematicChunkRenderContainerVbo.java:28)
> 	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderBlockLayer(RenderSchematic.java:802)
> 	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.func_174977_a(RenderSchematic.java:793)
> 	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderWorld(RenderSchematic.java:352)
> 	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderSchematic(RenderSchematic.java:278)
> 	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.onRenderWorldLast(RenderSchematic.java:247)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_22_RenderSchematic_onRenderWorldLast_RenderWorldLastEvent.invoke(.dynamic)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
> 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
> 	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:181)
> 	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at net.optifine.reflect.Reflector.callVoid(Reflector.java:660)
> 	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1951)
> 	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1613)
> 	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1384)
> 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
> 	at net.minecraft.client.main.Main.main(SourceFile:123)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Client thread
> Stacktrace:
> 	at java.nio.Buffer.nextPutIndex(Buffer.java:521)
> 	at java.nio.DirectIntBufferU.put(DirectIntBufferU.java:297)
> 	at net.optifine.render.VboRegion.drawArrays(VboRegion.java:299)
> 	at net.minecraft.client.renderer.vertex.VertexBuffer.func_177358_a(VertexBuffer.java:50)
> 	at com.github.lunatrius.schematica.client.renderer.chunk.container.SchematicChunkRenderContainerVbo.func_178001_a(SchematicChunkRenderContainerVbo.java:28)
> 	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderBlockLayer(RenderSchematic.java:802)
> 	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.func_174977_a(RenderSchematic.java:793)
> 	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderWorld(RenderSchematic.java:352)
> 	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.renderSchematic(RenderSchematic.java:278)
> 	at com.github.lunatrius.schematica.client.renderer.RenderSchematic.onRenderWorldLast(RenderSchematic.java:247)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_22_RenderSchematic_onRenderWorldLast_RenderWorldLastEvent.invoke(.dynamic)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
> 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
> 	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:181)
> 	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at net.optifine.reflect.Reflector.callVoid(Reflector.java:660)
> 	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1951)
> 	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1613)
> 
> -- Affected level --
> Details:
> 	Level name: MpServer
> 	All players: 1 total; [EntityPlayerSP['Dannythebrill13'/55, l='MpServer', x=3.52, y=69.97, z=38.75]]
> 	Chunk stats: MultiplayerChunkCache: 800, 800
> 	Level seed: 0
> 	Level generator: ID 01 - flat, ver 0. Features enabled: false
> 	Level generator options: 
> 	Level spawn location: World: (45,4,60), Chunk: (at 13,0,12 in 2,3; contains blocks 32,0,48 to 47,255,63), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
> 	Level time: 3162 game time, 3162 day time
> 	Level dimension: 0
> 	Level storage version: 0x00000 - Unknown?
> 	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
> 	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
> 	Forced entities: 25 total; [EntityPig['Pig'/0, l='MpServer', x=-25.78, y=64.00, z=17.26], EntityHorse['Horse'/1, l='MpServer', x=-45.85, y=64.00, z=76.83], EntitySheep['Sheep'/2, l='MpServer', x=-37.50, y=64.00, z=71.50], EntitySheep['Sheep'/3, l='MpServer', x=-39.50, y=64.00, z=68.50], EntitySheep['Sheep'/4, l='MpServer', x=-35.50, y=64.00, z=66.50], EntityPig['Pig'/5, l='MpServer', x=-30.57, y=64.00, z=14.91], EntityPig['Pig'/6, l='MpServer', x=-22.70, y=64.00, z=21.24], EntityPig['Pig'/7, l='MpServer', x=-24.76, y=64.00, z=10.57], EntitySheep['Sheep'/8, l='MpServer', x=-20.78, y=64.00, z=83.84], EntitySheep['Sheep'/9, l='MpServer', x=-24.50, y=64.00, z=90.50], EntitySheep['Sheep'/10, l='MpServer', x=-23.50, y=64.00, z=92.50], EntitySheep['Sheep'/11, l='MpServer', x=-20.50, y=64.00, z=96.50], EntitySheep['Sheep'/15, l='MpServer', x=-2.50, y=64.00, z=63.50], EntitySheep['Sheep'/16, l='MpServer', x=-3.50, y=64.00, z=64.50], EntitySheep['Sheep'/18, l='MpServer', x=1.30, y=64.00, z=65.28], EntitySheep['Sheep'/19, l='MpServer', x=3.24, y=64.00, z=62.42], EntityCow['Cow'/20, l='MpServer', x=17.83, y=64.00, z=69.33], EntityCow['Cow'/21, l='MpServer', x=27.26, y=64.00, z=55.86], EntityCow['Cow'/22, l='MpServer', x=32.43, y=64.00, z=54.80], EntityCow['Cow'/23, l='MpServer', x=16.82, y=64.00, z=66.43], EntityCow['Cow'/24, l='MpServer', x=45.62, y=64.00, z=13.79], EntityCow['Cow'/25, l='MpServer', x=44.50, y=64.00, z=13.81], EntityCow['Cow'/26, l='MpServer', x=45.72, y=64.00, z=25.18], EntitySheep['Sheep'/27, l='MpServer', x=49.37, y=64.00, z=23.24], EntityPlayerSP['Dannythebrill13'/55, l='MpServer', x=3.52, y=69.97, z=38.75]]
> 	Retry entities: 0 total; []
> 	Server brand: fml,forge
> 	Server type: Integrated singleplayer server
> Stacktrace:
> 	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
> 	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2740)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
> 	at net.minecraft.client.main.Main.main(SourceFile:123)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.12.2
> 	Operating System: Windows 10 (amd64) version 10.0
> 	Java Version: 1.8.0_51, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 224806272 bytes (214 MB) / 637534208 bytes (608 MB) up to 3221225472 bytes (3072 MB)
> 	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
> 	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
> 	FML: MCP 9.42 Powered by Forge 14.23.5.2768 Optifine OptiFine_1.12.2_HD_U_E3 6 mods loaded, 6 mods active
> 	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
> 
> 	| State     | ID            | Version      | Source                                      | Signature                                |
> 	|:--------- |:------------- |:------------ |:------------------------------------------- |:---------------------------------------- |
> 	| UCHIJAAAA | minecraft     | 1.12.2       | minecraft.jar                               | None                                     |
> 	| UCHIJAAAA | mcp           | 9.42         | minecraft.jar                               | None                                     |
> 	| UCHIJAAAA | FML           | 8.0.99.99    | forge-1.12.2-14.23.5.2768.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
> 	| UCHIJAAAA | forge         | 14.23.5.2768 | forge-1.12.2-14.23.5.2768.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
> 	| UCHIJAAAA | lunatriuscore | 1.2.0.42     | LunatriusCore-1.12.2-1.2.0.42-universal.jar | None                                     |
> 	| UCHIJAAAA | schematica    | 1.8.0.169    | Schematica-1.12.2-1.8.0.169-universal.jar   | None                                     |
> 
> 	Loaded coremods (and transformers): 
> 	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 430.86' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
> 	Launched Version: 1.12.2-forge1.12.2-14.23.5.2768
> 	LWJGL: 2.9.4
> 	OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 430.86, NVIDIA Corporation
> 	GL Caps: Using GL 1.3 multitexturing.
> Using GL 1.3 texture combiners.
> Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
> Shaders are available because OpenGL 2.1 is supported.
> VBOs are available because OpenGL 1.5 is supported.
> 
> 	Using VBOs: Yes
> 	Is Modded: Definitely; Client brand changed to 'fml,forge'
> 	Type: Client (map_client.txt)
> 	Resource Packs: vanilla, file/Edited Default Textures (2).zip
> 	Current Language: English (US)
> 	Profiler Position: N/A (disabled)
> 	CPU: 4x AMD Athlon(tm) X4 880K Quad Core Processor

**Comment by Thedeur** [comment]
Do you have Optifine and its "Render Regions" setting enabled? It seems to be an incompatibility, and once you disable it Schematica works fine again. 

I too had this issue until I found the fix (Issue #321).
