### ISSUE TITLE
Allow players to rotate/flip objects on any axis

### ISSUE THREAD

**Issue by NAYF1N** [Lunatrius/Schematica#45]
I'm wondering if it is possible to be able to flip an object from a horizontal position to vertical, on the Z-axis of a 3D coordinate plane. We are able to rotate objects around and around all day long having as much fun as we possibly can, but it would be wicked cool if we could if we could also flip them at 90 degree intervals. Just like bowties. Bowties are cool.

Okay maybe not quite like bowties, but you get the picture. Thoughts?

**Comment by Arcrammer** [comment]
Do you know what would absolutely blow me away? Allowing the user to rotate items 45º too. That would take a lot of work!

**Comment by Lunatrius** [comment]
Was added in 452f2d60a1e06192a372e07ea1e729442d8f7a40, flipping might come at a later time (if needed at all).
