### ISSUE TITLE
Allow player movements while in menus

### ISSUE THREAD

**Issue by lucom** [Lunatrius/Schematica#48]
It would be great to be able to move the player while positioning a schematic in the world. Also changing the view angle would be great. So my suggestion would be:

As long as no TextBox is selected the player should be able to walk using the default buttons.
While right clicking one should be able to change the view direction: Drag to look into another direction.

**Comment by Lunatrius** [comment]
Moved this to the master issue (#102) for features that would be better of as an addon, but might be added to the mod itself.
