### ISSUE TITLE
Select / filter / replace blocks in a schematic

### ISSUE THREAD

**Issue by lucom** [Lunatrius/Schematica#49]
Another idea: When selecting the area that should be exported as a schematic, it would be great if one could browse through the different blocks needed for that part (like in the Materials list). There one should be able to select or deselect the blocks that should be saved or not.

For example (x = selected):
- X Dirt
- X Cobble Stone
- _ Sand
- _ Grass
- X Glass

The same selection would be great while "printing" the schematic. So one could start with the scaffold based on e.g. dirt and stone blocks and later on select all other remaining blocks.

**Comment by Protheus** [comment]
would love to see this in 1.7.10, replace an existing block with something else before starting the print

**Comment by Lunatrius** [comment]
I'll be most likely backporting these features from 1.8 when they're added. Wanted to get them all in, but turns out there's a few other things I have to improve first.

**Comment by Protheus** [comment]
Take your time love the mod.

**Comment by EvilYodeler** [comment]
Love the mod!! Been patiently waiting for 1.8  :) A thought that I had on the change/replace block would be that you click the block in the materials list then in the popup GUI you can choose "Change" or "Remove". Change GUI would present you with an entry line for ID/Name and/or the ability to choose from a full listing of blocks. Just a thought...  i know whatever you do, should be awesome!!

**Comment by Lunatrius** [comment]
Initial version implemented in a4d584a25ebd20318efa54ea5083eb1242b8c4a4. Just a command for the time being.

**Comment by aeneasr** [comment]
Is it possible to save changes made with `/schematicaReplace`? I don't want to run it every time :)
