### ISSUE TITLE
Change order of placing blocks when using the printer

### ISSUE THREAD

**Issue by lucom** [Lunatrius/Schematica#50]
When using the printer it always starts placing blocks in one specific corner (north west top or something) and then continues with all reachable adjacent blocks. It would be great if the printer could start placing the blocks that are next to the "cursor" where the player normally would place a block.

**Comment by lucom** [comment]
Just a stupid idea how you could solve that without a performance issue.

Since you always try to place the blocks around you, which is at max 7*7 blocks, you could just define an array with the intended order of x,y,z coordinates that should be filled. Like:

{0,0,0},{-1,0,0},{+1,0,0},{0,0,-1}...{-2,1,0},{-2,1,1}... etc.

That way you wouldn't need any kind of "logic". Instead you could simply iterate through the predefined coordinates (relative to the players position or cursor or whatever is possible).

It might make sense to write a short script that creates that array.

**Comment by Lunatrius** [comment]
Did you mean from the *player* or the *mouse over block*? For the player a lookup matrix might make sense, but for the mouse over... nope. You'd need 7^3 matrices each containing 7^3 coordinates in the processing order.

I'll revise all the options once I manage to rewrite the entire printer. Still working on the rendering parts at the moment.

**Comment by lucom** [comment]
Well, the player should be OK as origin.
But for the mouse over block you could use a smaller matrix/array and fill the rest with the for loops...

**Comment by Lunatrius** [comment]
Moved this to the master issue (#102) for features that would be better of as an addon, but might be added to the mod itself.
