### ISSUE TITLE
Support Server-side schematics

### ISSUE THREAD

**Issue by AtomicBlom** [Lunatrius/Schematica#53]
In order to support larger schematics and accurate tile-entity tracking, I'd like to implement the ability to save a schematic on the server side.

Issues that we've started discussing:
* We need the schematic to be transferred back to the client.
** This data will need to be sent in a manner that does not murder the performance of the server and/or client.
* Chunk Loading will be an issue with large scale schematics.
* Limits will need to be imposed on schematic size, transfer speeds.

**Comment by Lunatrius** [comment]
Going to close this for now, the main commands have already been implemented. Will try to write down everything that still has to be done and open up a new issue for that.
