### ISSUE TITLE
Add option to ignore snow layer blocks when displaying a schematic.

### ISSUE THREAD

**Issue by starcraft66** [Lunatrius/Schematica#62]
I happen to be finding myself building in snow biomes a lot on 2b2t with schematica and it is really annoying when it starts snowing and the little snow layer blocks start forming and appear as invalid blocks in red on the ghost schematic. It would be really nice if a feature could be implemented to ignore the snow layers since you can replace the block with any other just by right clicking it like grass.

**Comment by Lunatrius** [comment]
You might be able to do this in the latest build now. However, anything with the blocks on the ignored list will **not** be highlighted at all.

**Comment by starcraft66** [comment]
Thanks man! I'll check it out soon.

On Sat, Jan 10, 2015 at 12:09 PM, Jadran Kotnik <notifications@github.com>
wrote:

> Closed #62 <https://github.com/Lunatrius/Schematica/issues/62>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Lunatrius/Schematica/issues/62#event-216982482>.
>



-- 

-Tristan
