### ISSUE TITLE
question: given any thought to another plugin loader?

### ISSUE THREAD

**Issue by intangir** [Lunatrius/Schematica#64]
i know forge is still not supporting 1.8 yet, but the beta/dev branch of it has had alot of issues for me, and it is incompatible with bungee/spigot

your mod is one of my favorites, i wonder how hard it would be to use another loader like http://www.liteloader.com/

it has alot fewer features but if its only missing features you don't need, which i think may be the case (at least for the ingame info xml one) it might be worth checking out

just a heads up

**Comment by Lunatrius** [comment]
Closing this.

If anyone feels like wanting to add LL (or any other loader) support or possibly maintain a separate version of the mod, feel free to contact me.
