### ISSUE TITLE
java.lang.IllegalAccessError: tried to access field

### ISSUE THREAD

**Issue by lucas88110** [Lunatrius/Schematica#65]
If you're getting this error in the console, please refer to the [FAQ](https://github.com/Lunatrius/Schematica/wiki/Frequently-Asked-Questions#javalangillegalaccesserror-tried-to-access-method--from-class-). If none of the proposed solutions work for you feel free to ask for help in this issue. -- @Lunatrius

---

I crash when I want to import a schematic
**Mod version:** 1.7.10
**Forge version:** forge-1.7.10-10.13.2.1230
**Operating system:** --Windows
**Mod list:**
 LunatriusCore-1.7.10-1.1.2.18-universal.jar;
OptiFine_1.7.10_HD_U_B4(1);
Schematica-1.7.10-1.7.3.105-universal.jar;
ShadersModCore-v2.3.28-mc1.7.10-f;
OpenEye-0.6-1.7.10

  * ...
**Crash report:** --FILL IN (upload to gist or pastebin)--

http://openeye.openmods.info/crashes/2e856fc2a89ad86fdb74eb6b7d224a60

http://pastebin.com/8H9RNTPk

**Comment by Felina-Lain** [comment]
I have the same problem, I think also the same error log
http://pastebin.com/zcx2f2pd
I use magic launcher for all my mods
and the schematica file is .jar and not .zip or .jar.zip
I don't get it....

**Comment by Lunatrius** [comment]
That's an issue with Magic Launcher. FML will only scan for FMLAT attributes (tl;dr: the thing that prevents this crash) in the `mods` folder OR mods passed in with the `--mods` argument.

Your only option is to either move the mod into the mods folder or switch to a different launcher. As a more permanent solution you'll have to ask the dev to use FML's `--mod` argument or switch to a different launcher. I personally prefer the MultiMC/vanilla launcher.

**Comment by Felina-Lain** [comment]
Oh, alright. I'll try mods folder and if it doesn't work I'll go for vanilla then
thanks ^^
