### ISSUE TITLE
feature request: schematic sorting?

### ISSUE THREAD

**Issue by intangir** [Lunatrius/Schematica#73]
I would like to see the schematic list sorted, i have quiet a few and finding them in the list is difficult

**Comment by Lunatrius** [comment]
They can be sorted using normal folder inside the schematic folder?

**Comment by intangir** [comment]
thanks that was actually pretty helpful

i just made a bunch of sub folders, much more managable

not sure why i didn't think of that

**Comment by Hund** [comment]
I would like to see this as well. I have folders, but it's still pretty stupid not have have the files in order.

**Comment by Lunatrius** [comment]
What kind of sorting? I'm a bit confused what other types of sort should be used (they're already sorted alphabetically).

**Comment by Hund** [comment]
It's not sorted according to the alphabet I'm using. :)

![2017-11-26_12 35 12](https://user-images.githubusercontent.com/320498/33239638-58b59b12-d2a6-11e7-9047-23493c057209.png)

**Comment by Pokechu22** [comment]
What OS are you using?

**Comment by Hund** [comment]
Linux. Arch Linux to be exact.

**Comment by Pokechu22** [comment]
Here's the code that lists schematics (subfolders happen earlier, not linked here):

https://github.com/Lunatrius/Schematica/blob/1216f96a1d24df0de562893c074da2824505cde9/src/main/java/com/github/lunatrius/schematica/client/gui/load/GuiSchematicLoad.java#L155-L165

[`File.listFiles`](https://docs.oracle.com/javase/8/docs/api/java/io/File.html#listFiles--) says:
> There is no guarantee that the name strings in the resulting array will appear in any specific order; they are not, in particular, guaranteed to appear in alphabetical order. 

I'm guessing that on Windows, they _do_ appear in alphabetical order, but on Arch Linux they don't.

**Comment by Hund** [comment]
Thank you! :)
