### ISSUE TITLE
i seem to crash about every 3 mins since implement of overlay

### ISSUE THREAD

**Issue by MrAndyPipkin** [Lunatrius/Schematica#77]
ever since the overlay i have been crashing ALOT roughly about every three mins or so i have latest forge and i have tried with nothing else running on my client and also my norm set up with lite loader and voxel map too anyway here is the pastebin of the crash report

http://pastebin.com/eBSjgMGu

**Comment by Lunatrius** [comment]
I was getting a similar crash at dev time, but eventually (I thought that) I fixed it. Will have to check why it might still get though.
