### ISSUE TITLE
Water and Lava textures on schematic overlay garbled

### ISSUE THREAD

**Issue by octarine-noise** [Lunatrius/Schematica#78]
If any mods are installed which register textures in the block atlas, water and lava on schematic overlays will have random garbled textures.

The reason is that **SchematicBlockRendererDispatcher** is not registered as a resource reload listener (the default dispatcher is), so the sprites (and UV coords) from the initial vanilla block atlas are used forever by the dispatcher's **BlockFluidRenderer**.

**Comment by Lunatrius** [comment]
Thanks! Must've missed it while trying to get the overlay working.
