### ISSUE TITLE
Schematica printer issues

### ISSUE THREAD

**Issue by RagingDanny1** [Lunatrius/Schematica#85]
Having loaded a schematic in to a server where i currently have creative allowances i turn on the printer and the blocks start flashing as though trying to place them.

However 99% of the time these disappear a moment later as not having placed. I am pretty sure this will only be an issue on my end but i can not find any way to fix this issue. i am currently having to manually build a large build and having the printer would assist me by far.

**Comment by RagingDanny1** [comment]
Ok i have atempted to use this in single player and there are no issues so i would assume its an issue within the server. however i have limited knowledge of what could be the specific cause of this so if you are able to point me in the right direction that would be brilliant

**Comment by Lunatrius** [comment]
It's an anti-cheat server plugin that forces strict rules on where and how blocks can be placed. Nothing I can do about that really.
