### ISSUE TITLE
1.8-1.7.7.132 crashes when entering a world

### ISSUE THREAD

**Issue by Freso** [Lunatrius/Schematica#87]
Logs at https://gist.github.com/Freso/1160ba37b4f6f2938ba1

1.8-1.7.7.131 works fine.

**Comment by Lunatrius** [comment]
Are you sure you grabbed the correct crash log?

**Comment by Lunatrius** [comment]
You most likely meant the crash related to 9e32ab290cc50d5f4aaf3938d4ab7967e2ebb645, which is fixed in build 133.

If the crash is still present feel free to re-open the issue.

**Comment by Freso** [comment]
Hm. I grabbed the …-latest.log, but it does indeed seem like the timestamps don't quite match up. I don't know what's going on.

**Comment by Freso** [comment]
Yep. Fixed in .133. Cheers. :)
