### ISSUE TITLE
Schematica renders false ghost blocks making it hard to see the real ghost blocks

### ISSUE THREAD

**Issue by Hund** [Lunatrius/Schematica#88]
Schematica renders false ghost blocks making it hard to see the real ghost blocks.

A picture on what I am talking about:

![2015-08-03_13 48 18](https://cloud.githubusercontent.com/assets/320498/9037053/85ef2828-39e7-11e5-883b-94c82419a1fe.png)

And this is what I copied:

![2015-08-03_13 50 16](https://cloud.githubusercontent.com/assets/320498/9037055/8acbf402-39e7-11e5-9516-a9d56bfdfc66.png)

Another picture from the back:

![2015-08-03_13 50 56](https://cloud.githubusercontent.com/assets/320498/9037057/8fd20ae0-39e7-11e5-85e9-1f4ae5fba260.png)

I'm using Forge 7.10.99.99 with [these mods](http://hastebin.com/lujuxowage).

**Comment by Lunatrius** [comment]
1.7.10? 1.8? What version? What other mods?

**Comment by Lunatrius** [comment]
Can you upload the schematic file? Or possibly save just the area with the fake blocks?

**Comment by Hund** [comment]
1.7.10. There's a link with the mods in the first post. And here's the
schematic file: https://www.dropbox.com/s/2kwwe1m3skqrkvx/1.schematic?dl=0

2015-08-03 14:17 GMT+02:00 Jadran Kotnik <notifications@github.com>:

**Comment by Lunatrius** [comment]
It's either `Railcraft:residual.heat` (or possibly `Thaumcraft:blockAiry`). Try adding the Railcraft block to the extra air block list in the Schematica config.

**Comment by Hund** [comment]
Oh, fancy. Didnt know you could do that. But, is this correct?

```
general {
    # Extra blocks to consider as air for the schematic renderer.
    S:extraAirBlocks <
        Railcraft:residual.heat
        Thaumcraft:blockAiry
     >
```
If so, it's not working. :(

**Comment by Lunatrius** [comment]
Right, forgot that that is just a hack for underwater building stuff... 00fd4758e7b034d5fca4097852a2f4fffad33d1b should fix the issue.

**Comment by Hund** [comment]
Great! Then I will play the waiting game until the next version. :)

**Comment by Lunatrius** [comment]
Was uploaded a few minutes ago.

**Comment by Hund** [comment]
At Curseforge?

**Comment by Lunatrius** [comment]
Yeah, and modsio. CF might've been a bit slow to approve it today.

**Comment by Hund** [comment]
Thanks! :) Never heard of modsio before.

**Comment by Lunatrius** [comment]
Gonna close this. If it happens again feel free to re-open.
