### ISSUE TITLE
Crash when "printing" double/tall grass - world get corrupted cannot be loaded after

### ISSUE THREAD

**Issue by MoonCutter2B** [Lunatrius/Schematica#89]
**Mod version:** Schematica-1.7.10-1.7.6.125-universal
**Forge version:** 1492
**Operating system:** Win7 pro 64 bit
**Mod list:** oh dear ;)
  *  [1.7.2] ChickenShed (v1.1.3).jar
  * AgriCraft-1.7.10-1.4.0-beta-1-1.7.10.jar
  * AOBD-2.8.1.jar
  * Aroma1997Core-1.7.10-1.0.2.14.jar
  * AromaBackup-1.7.10-0.0.0.5.jar
  * bdlib-1.9.1.97-mc1.7.10.jar
  * BiblioCraft[v1.10.5][MC1.7.10].jar
  * BiblioWoods[BiomesOPlenty][v1.9].jar
  * binnie-mods-2.0-pre14.jar
  * BiomesOPlenty-1.7.10-2.1.0.1364-universal.jar
  * buildcraft-7.0.20.jar
  * buildcraft-compat-7.0.8.jar
  * ChickenChunks-1.7.10-1.3.4.19-universal.jar
  * Chisel2-2.4.1.40.jar
  * CoFHCore-[1.7.10]3.0.3-303.jar
  * ComputerCraft1.74.jar
  * CustomMainMenu-MC1.7.10-1.6.jar
  * denseores-1.6.2.jar
  * EnderIO-1.7.10-2.2.8.381.jar
  * EnderStorage-1.7.10-1.4.7.33-universal.jar
  * EnderTech-1.7.10-0.3.2.388.jar
  * ExtraTiC-1.7.10-1.4.5.jar
  * extrautilities-1.2.9.jar
  * fastcraft-1.21.jar
  * [forestry_1.7.10-3.6.3.20.jar
  * gendustry-1.5.2.107-mc1.7.10.jar
  * iChunUtil-4.2.2.jar
  * INpureCore-[1.7.10]1.0.0B9-62.jar
  * InventoryTweaks-1.59-dev-152.jar
  * ironchest-1.7.10-6.0.62.742-universal.jar
  * Jabba-1.2.1a_1.7.10.jar
  * journeymap-1.7.10-5.1.0-unlimited.jar
  * logisticspipes-0.9.2.30.jar
  * LunatriusCore-1.7.10-1.1.2.21-universal.jar
  * magicalcrops-4.0.0_PUBLIC_BETA_5.jar
  * magicbees-1.7.10-2.3.3.jar
  * Mantle-1.7.10-0.3.2.jar
  * Mekanism-1.7.10-8.1.7.252.jar
  * MekanismGenerators-1.7.10-8.1.7.252.jar
  * MekanismTools-1.7.10-8.1.7.252.jar
  * MFR Compat - Magical Crops v1-2-1.jar
  * MineFactoryReloaded-[1.7.10]2.8.0-104.jar
  * MineTweaker3-1.7.10-3.0.9C.jar
  * natura-1.7.10-2.2.0.1.jar
  * neiaddons-1.12.11.36-mc1.7.10.jar
  * NEIIntegration-MC1.7.10-1.0.12.jar
  * NetherOres-[1.7.10]2.3.0-12.jar
  * NotEnoughKeys-1.7.10-1.0.0b29.jar
  * NotEnoughResources-1.7.10-0.1.0.106.jar
  * OpenBlocks-1.7.10-1.4.4.jar
  * OpenModsLib-1.7.10-0.8.jar
  * OpenPeripheralAddons-1.7.10-0.4.jar
  * OpenPeripheralCore-1.7.10-1.2.jar
  * OpenPeripheralIntegration-1.7.10-0.3.jar
  * Pam's HarvestCraft 1.7.10j.jar
  * ProjectRed-1.7.10-4.7.0pre8.92-Base.jar
  * ProjectRed-1.7.10-4.7.0pre8.92-Compat.jar
  * ProjectRed-1.7.10-4.7.0pre8.92-Integration.jar
  * ProjectRed-1.7.10-4.7.0pre8.92-Lighting.jar
  * ProjectRed-1.7.10-4.7.0pre8.92-Mechanical.jar
  * ProjectRed-1.7.10-4.7.0pre8.92-World.jar
  * railcraft
  * Railcraft_1.7.10-9.6.1.0.jar
  * RandomThings-2.2.4.jar
  * RedstoneArsenal-[1.7.10]1.1.1-89.jar
  * ResourceEngineering-1.7.10-2.0.89.jar
  * ResourceLoader-1.2.jar
  * roguelike-1.7.10-1.3.6.3.jar
  * Schematica-1.7.10-1.7.6.125-universal.jar
  * SolarExpansion-Basic-1.6a.jar
  * StevesAddons-1.7.10-0.10.16.jar
  * StevesCarts2.0.0.b18.jar
  * StevesFactoryManagerA93.jar
  * StevesWorkshop-0.5.1.jar
  * StorageDrawers-1.7.10-1.5.12.jar
  * TConstruct-1.7.10-1.8.5.jar
  * ThermalDynamics-[1.7.10]1.1.0-161.jar
  * ThermalExpansion-[1.7.10]4.0.3B1-218.jar
  * ThermalFoundation-[1.7.10]1.2.0-102.jar
  * ThermalRecycling-1.7.10-0.4.2.7.jar
  * TiCTooltips-mc1.7.10-1.2.5.jar
  * TMechworks-1.7.10-0.2.14.100.jar
  * ttCore-MC1.7.10-0.1.1-78.jar
  * Waila-1.5.10_1.7.10.jar
  * WailaHarvestability-mc1.7.x-1.1.2.jar
  * Wawla-1.3.1-1.7.10.jar
  * WR-CBE-1.7.10-1.4.1.9-universal.jar 

**Crash report:** https://dl.dropboxusercontent.com/u/58751759/crash-2015-08-08_08.08.54-client.txt

I'm trying to "print" a huge schematic. Done mostly in Survival layer by layer. 
But this happens when I'm in creative trying to fix some incorrect blocks and add some missing ones.
So far it only happens when printing double grass, i.e. the two block high grass. 
And I get a felling that the crash happens when trying to print the upper block when there is no space below and or v.v. 
Placing  double grass layer by layer if both blocks are empty works.

**Comment by MoonCutter2B** [comment]
I guess that the code used for handling doors could be useful for this?

**Comment by Lunatrius** [comment]
It's not that there are no free blocks, it's the block that it picked up that has incorrect metadata. You should be able to recover the world by just deleting the player file or by removing the tall grass item from the inventory using NBTExplorer.

I'll look into this and see if I can backport the 1.8 code without messing up anything major.

**Comment by Lunatrius** [comment]
c53e8eec8e532c214daaee048eb6d8fad285706a should prevent invalid items from being created in the future. If you still experience the same crash, feel free to re-open the issue.

Also, should you need help recovering the player file you can poke me on [EsperNET](http://webchat.esper.net/?nick=&channels=%23lunatrius).

**Comment by MoonCutter2B** [comment]
I use Aroma backup so I can manage, thanks for update!
