### ISSUE TITLE
Suggestion : Develop the printer in survival mode

### ISSUE THREAD

**Issue by Zarbuz** [Lunatrius/Schematica#91]
There are many things that can be implemented in survival mode:
- Retrieve resources from a chest that must be put to some coordinates.
- Put "scaffolding" in the ground for buildings which have great height
- (In a far future ? Maybe another mod ?) A automove?

**Comment by Lunatrius** [comment]
As great as it sounds, this is something that I most likely won't implement as part of Schematica. All of the described points are basically AI tasks that control the player, which is anything but trivial to do.

Retrieving resources from the chests is most likely the easiest thing, but actually moving around and placing/removing scaffoldings around the place is something that might be better off as an *experimental* add-on for the mod.

**Comment by Lunatrius** [comment]
Moved this to the master issue (#102) for features that would be better of as an addon, but might be added to the mod itself.
