### ISSUE TITLE
Schematica remove blocks too?

### ISSUE THREAD

**Issue by zD12** [Lunatrius/Schematica#92]
Hi there,
Is it possible to add Schematica to automatically mine?  It wouldn't be cheating, as you'd have to have the actual pickaxes and move around.   I am sorry if this was already submitted, but, it'd be very helpful.

**Comment by Lunatrius** [comment]
Currently only creative mode is supported. The reason why it's not in survival (yet) is that it's not an easy task to mine blocks (different tool types, speed, actually keep the tools selected and in use etc).

**Comment by zD12** [comment]
Oh, okay- thank you for the fast response.  Amazing work, and I hope you continue your works.  

(PS: The community wouldn't mind Adfly's, besides, it's smart idea)

**Comment by Lunatrius** [comment]
"Adfly's", as in the paid link shortener? I've stopped using that over a year ago, in favor of modsio and curseforge.
