### ISSUE TITLE
Double Slabs

### ISSUE THREAD

**Issue by StarfireSky** [Lunatrius/Schematica#93]
Schematica is having trouble with the double slabs when I go to build a building that has double slabs on it it will not double slab the building I have to stop it and go back and double slab the whole building and I am starting to hate the mod.

**Comment by Lunatrius** [comment]
* Minecraft version?
* Schematica version?
* What kind of slabs?
* Does it place them at all or does it skip them?
* Where did you download the schematic (or did you create it yourself)?

**Comment by StarfireSky** [comment]
Minecraft version 1.7.10

Schematica 1.7.10 1.7.6.128

Slabs are double Stone slab it does not double the stone slab it just puts down the single stone slab.
 
The schematic is I copy a building that has a lot of double stone slab.

**Comment by Lunatrius** [comment]
1.7.10 currently doesn't have the printer tweak that allows the printer to place double slabs correctly. I'm not sure when I'll have the time to backport it from 1.8, but it definitely won't be in the next two weeks due to some other activities I have to take care of.

**Comment by StarfireSky** [comment]
Now if I use the schematica version 1.7.10-1.7.6.125 it uses the double stone slab just fine so why is it different than the 1.7.10-1.7.6.128

**Comment by Lunatrius** [comment]
Are you building in creative mode? And what slabs exactly are failing to place correctly?

**Comment by StarfireSky** [comment]
Yes I am building in creative mode and the slabs that are failing to be place are the double stone slabs are to ones that are failing to be place correctly that is why I had to go from version 1.7.10-1.7.6.128 to 1.7.10-1.7.6.125 just to use the double stone slabs.

**Comment by Lunatrius** [comment]
I forgot to port over some of the 1.8 code that handles slab placement. Latest version should work fine.
