### ISSUE TITLE
No Red or Blue blocks!

### ISSUE THREAD

**Issue by CanDoCool** [Lunatrius/Schematica#94]
Whenever I press "*"  it opens the save schematic GUI however, it doesn't show either the Red or Blue boxes that are used to align the schematics 'borders'.

Please help!

**Comment by Lunatrius** [comment]
https://github.com/Lunatrius/Schematica/wiki/Saving-schematic-files

> Points can be made visible by clicking the `OFF` button in the bottom right corner of the screen.

**Comment by Lunatrius** [comment]
Closing this. If you experience the same issue even after clicking the `OFF` button feel free to reopen the issue and supply additional information (mods, versions etc).
